# Webscraping 2.0

Joseph Nelson, DC

In today's codealong, I'll walkthrough how to build a scraper using urllib and BeautifulSoup. We'll discover the problems we discussed in the lesson readme associated with doing so, and we'll remedy this problem using a headless browser called Selenium.

In [90]:
# import
from selenium import webdriver
from time import sleep
from bs4 import BeautifulSoup
import urllib

## Data_Analyst_DC_60_entry

In [91]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000&l=Washington,+DC&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_60_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_60_entry

,Company_name,Location,Salary,Title,Experience
0,GEICO,"Chevy Chase, MD",60000.0,Data_Analyst,Entry_level
1,Evolent Health,"Arlington, VA 22203",60000.0,Data_Analyst,Entry_level
2,Datalogic Solutions Inc,"Chantilly, VA",60000.0,Data_Analyst,Entry_level
3,Cipher3,"Washington, DC",60000.0,Data_Analyst,Entry_level
4,"Interfolio, Inc","Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Entry_level
5,JLL,"Washington, DC",60000.0,Data_Analyst,Entry_level
6,Goodwill Excel Center - DC,"Washington, DC",60000.0,Data_Analyst,Entry_level
7,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Entry_level
8,Grant Thornton,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Entry_level
9,FAAZ Consulting LLC,"Washington, DC",60000.0,Data_Analyst,Entry_level
10,Centra Technology,"Washington, DC",60000.0,Data_Analyst,Entry_level
11,Smithsonian Institution,"Washington, DC",60000.0,Data_Analyst,Entry_level
12,Booz Allen Hamilton,"Alexandria, VA",60000.0,Data_Analyst,Entry_level
13,Booz Allen Hamilton,"McLean, VA",60000.0,Data_Analyst,Entry_level
14,Advanced Software Systems,"Arlington, VA",60000.0,Data_Analyst,Entry_level
15,Booz Allen Hamilton,"Silver Spring, MD",60000.0,Data_Analyst,Entry_level
16,AOL,"Baltimore, MD",60000.0,Data_Analyst,Entry_level
17,US News & World Report,"Washington, DC 20007 (Georgetown area)",60000.0,Data_Analyst,Entry_level
18,AER,"College Park, MD",60000.0,Data_Analyst,Entry_level
19,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Entry_level
20,Deloitte,"Arlington, VA 22209 (Radnor-Ft Myer Heights area)",60000.0,Data_Analyst,Entry_level
21,GEICO,"Chevy Chase, MD",60000.0,Data_Analyst,Entry_level
22,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Entry_level
23,DISYS,"McLean, VA",60000.0,Data_Analyst,Entry_level
24,Korn Ferry/Futurestep,"Washington, DC",60000.0,Data_Analyst,Entry_level
25,ICF International,"Fairfax, VA",60000.0,Data_Analyst,Entry_level
26,Alltech International,"Washington, DC",60000.0,Data_Analyst,Entry_level
27,Grant Thornton,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Entry_level
28,Accenture,"Rosslyn, VA",60000.0,Data_Analyst,Entry_level
29,Alliance of Community Health Plans,"Washington, DC",60000.0,Data_Analyst,Entry_level
...,...,...,...,...,...
75,BitVoyant,"Rosslyn, VA",60000.0,Data_Analyst,Entry_level
76,Gryphon Scientific,"Takoma Park, MD",60000.0,Data_Analyst,Entry_level
77,Atlas Research,"Washington, DC 20005 (Logan Circle area)",60000.0,Data_Analyst,Entry_level
78,Booz Allen Hamilton,"Fort Meade, MD",60000.0,Data_Analyst,Entry_level
79,"Measure UAS, Inc.","Washington, DC",60000.0,Data_Analyst,Entry_level
80,Aon,"Hunt Valley, MD",60000.0,Data_Analyst,Entry_level
81,Trinity Global Consulting,"Springfield, VA",60000.0,Data_Analyst,Entry_level
82,SyApps LLC,"Washington, DC",60000.0,Data_Analyst,Entry_level
83,REDHORSE CORPORATION,"Arlington, VA 22202 (Aurora Highlands area)",60000.0,Data_Analyst,Entry_level
84,Acumen LLC,"Washington, DC",60000.0,Data_Analyst,Entry_level
85,Grant Thornton,"Alexandria, VA 22314 (Southwest Quadrant area)",60000.0,Data_Analyst,Entry_level
86,"ActioNet, Inc.","Silver Spring, MD 20910",60000.0,Data_Analyst,Entry_level
87,TDI,"Quantico, VA",60000.0,Data_Analyst,Entry_level
88,Centeva,"Frederick, MD",60000.0,Data_Analyst,Entry_level
89,OBXtek,"Washington, DC",60000.0,Data_Analyst,Entry_level
90,Cvent,"Tysons Corner, VA",60000.0,Data_Analyst,Entry_level
91,"Computer Aid, Inc.(CAI)","Baltimore, MD",60000.0,Data_Analyst,Entry_level
92,Grant Thornton,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Entry_level
93,ASET Partners,"Washington, DC",60000.0,Data_Analyst,Entry_level
94,CapTech Consulting,"Reston, VA",60000.0,Data_Analyst,Entry_level
95,ASET Partners,"Washington, DC",60000.0,Data_Analyst,Entry_level
96,THRUUE,"Washington, DC",60000.0,Data_Analyst,Entry_level
97,Harris Corporation,"Annapolis Junction, MD 20701",60000.0,Data_Analyst,Entry_level
98,Driven Inc.,"Falls Church, VA",60000.0,Data_Analyst,Entry_level
99,"LS Technologies, LLC","Washington, DC",60000.0,Data_Analyst,Entry_level
100,"GreenZone Solutions, Inc.","Washington, DC 20001 (Shaw area)",60000.0,Data_Analyst,Entry_level
101,Olsen Palmer LLC,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Entry_level
102,Leidos,"Frederick, MD 21702",60000.0,Data_Analyst,Entry_level
103,"The Upside Travel Company, LLC","Washington, DC",60000.0,Data_Analyst,Entry_level
104,Deloitte,"Arlington, VA 22209",60000.0,Data_Analyst,Entry_level

## Data_Analyst_DC_60_mid

In [92]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000%2B&l=Washington,+DC&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_60_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_60_mid

,Company_name,Location,Salary,Title,Experience
0,ICF International,"Rockville, MD",60000.0,Data_Analyst,Mid_level
1,Truth Initiative,"Washington, DC 20001",60000.0,Data_Analyst,Mid_level
2,Net ESolutions Corporation (NETE),"Rockville, MD",60000.0,Data_Analyst,Mid_level
3,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",60000.0,Data_Analyst,Mid_level
4,Dixon Hughes Goodman LLP,"Washington, DC 20016 (AU-Tenleytown area)",60000.0,Data_Analyst,Mid_level
5,The World Bank,"Washington, DC",60000.0,Data_Analyst,Mid_level
6,Compumatics Group,"New Carrollton, MD",60000.0,Data_Analyst,Mid_level
7,DIT Inc,"Washington, DC",60000.0,Data_Analyst,Mid_level
8,Inforeem,"Washington, DC",60000.0,Data_Analyst,Mid_level
9,BCT Partners,"Washington, DC",60000.0,Data_Analyst,Mid_level
10,MAXIMUS,"Washington, DC 20002 (Capitol Hill area)",60000.0,Data_Analyst,Mid_level
11,ICF International,"Fairfax, VA",60000.0,Data_Analyst,Mid_level
12,CAVA,"Washington, DC 20009 (U Street Corridor area)",60000.0,Data_Analyst,Mid_level
13,Adept Solutions,"Washington, DC",60000.0,Data_Analyst,Mid_level
14,Salient CRGT,"Washington, DC",60000.0,Data_Analyst,Mid_level
15,"The Center for Organizational Excellence, ...","Washington, DC",60000.0,Data_Analyst,Mid_level
16,CRGT Inc.,"Washington, DC",60000.0,Data_Analyst,Mid_level
17,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Mid_level
18,American Institutes for Research,"Washington, DC",60000.0,Data_Analyst,Mid_level
19,The World Bank Group,"Washington, DC",60000.0,Data_Analyst,Mid_level
20,Legal Services Corporation,"Washington, DC",60000.0,Data_Analyst,Mid_level
21,Halfaker and Associates,"Washington, DC",60000.0,Data_Analyst,Mid_level
22,"MV Transportation, Inc.","Washington, DC",60000.0,Data_Analyst,Mid_level
23,Cystic Fibrosis Foundation,"Bethesda, MD 20814",60000.0,Data_Analyst,Mid_level
24,Excella Consulting,"Washington, DC 20006 (Foggy Bottom area)",60000.0,Data_Analyst,Mid_level
25,Capgemini Government Solutions,"Washington, DC",60000.0,Data_Analyst,Mid_level
26,Dixon Hughes Goodman LLP,"McLean, VA 22102",60000.0,Data_Analyst,Mid_level
27,Grant Thornton,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Mid_level
28,Salient CRGT,"Washington, DC",60000.0,Data_Analyst,Mid_level
29,CRGT Inc.,"Washington, DC",60000.0,Data_Analyst,Mid_level
...,...,...,...,...,...
75,Metacoastal,"Glen Burnie, MD 21061",60000.0,Data_Analyst,Mid_level
76,Exelon,"Washington, DC",60000.0,Data_Analyst,Mid_level
77,Management Analysis Technologies Inc.,"Washington, DC",60000.0,Data_Analyst,Mid_level
78,Systems Planning and Analysis,"Alexandria, VA 22311 (Alexandria Wrest area)",60000.0,Data_Analyst,Mid_level
79,Leidos,"Bethesda, MD 20813",60000.0,Data_Analyst,Mid_level
80,MetroStar Systems,"Washington, DC",60000.0,Data_Analyst,Mid_level
81,Prometric,"Nottingham, MD",60000.0,Data_Analyst,Mid_level
82,Logistics Management Institute,"Washington, DC",60000.0,Data_Analyst,Mid_level
83,George Washington University,"Ashburn, VA 20147",60000.0,Data_Analyst,Mid_level
84,Prism Inc.,"Arlington, VA",60000.0,Data_Analyst,Mid_level
85,"VISUAL SOFT, INC","Washington, DC",60000.0,Data_Analyst,Mid_level
86,Net ESolutions Corporation (NETE),"Rockville, MD",60000.0,Data_Analyst,Mid_level
87,xometry,"Bethesda, MD",60000.0,Data_Analyst,Mid_level
88,NetCentrics Corporation,"Washington, DC",60000.0,Data_Analyst,Mid_level
89,Karsun Solutions LLC,"Herndon, VA",60000.0,Data_Analyst,Mid_level
90,Project Enhancement Corp,"Washington, DC",60000.0,Data_Analyst,Mid_level
91,Booz Allen Hamilton,"Herndon, VA",60000.0,Data_Analyst,Mid_level
92,Valorous,"Washington, DC",60000.0,Data_Analyst,Mid_level
93,Information Innovators Inc.,"Alexandria, VA",60000.0,Data_Analyst,Mid_level
94,NTT DATA Services,"Ashburn, VA",60000.0,Data_Analyst,Mid_level
95,Bloomberg BNA,"Arlington, VA",60000.0,Data_Analyst,Mid_level
96,IntelliWare Systems,"Crystal City, VA",60000.0,Data_Analyst,Mid_level
97,EDC Consulting,"Washington, DC",60000.0,Data_Analyst,Mid_level
98,SA Solutions Inc. (SAS),"Lanham, MD",60000.0,Data_Analyst,Mid_level
99,"Washington & West, LLC","Baltimore, MD 21204",60000.0,Data_Analyst,Mid_level
100,Archimedes Global,"Alexandria, VA",60000.0,Data_Analyst,Mid_level
101,"Universal Strategy Group, Inc (USGI)","Washington, DC 20535 (Downtown area)",60000.0,Data_Analyst,Mid_level
102,ManTech International Corporation,"Silver Spring, MD",60000.0,Data_Analyst,Mid_level
103,Unisys,"Reston, VA",60000.0,Data_Analyst,Mid_level
104,Bay State,"Washington, DC",60000.0,Data_Analyst,Mid_level

## Data_Analyst_DC_60_senior

In [93]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000%2B&l=Washington,+DC&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_60_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_60_senior

,Company_name,Location,Salary,Title,Experience
0,Deloitte,"Arlington, VA 22209",60000.0,Data_Analyst,Senior_level
1,The BOSS Group,"Washington, DC",60000.0,Data_Analyst,Senior_level
2,General Dynamics Information Technology,"Washington, DC",60000.0,Data_Analyst,Senior_level
3,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
4,DataNet Systems Corporation,"Washington, DC",60000.0,Data_Analyst,Senior_level
5,ANSER,"Arlington, VA 22206 (Fairlington-Shirlington a...",60000.0,Data_Analyst,Senior_level
6,"Group Benefit Services, Inc.","Cockeysville, MD 21030",60000.0,Data_Analyst,Senior_level
7,Indev,"Washington, DC",60000.0,Data_Analyst,Senior_level
8,General Dynamics Information Technology,"Washington, DC",60000.0,Data_Analyst,Senior_level
9,General Dynamics Information Technology,"Towson, MD",60000.0,Data_Analyst,Senior_level
10,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",60000.0,Data_Analyst,Senior_level
11,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",60000.0,Data_Analyst,Senior_level
12,PricewaterhouseCoopers LLC,"Washington, DC 20001 (Shaw area)",60000.0,Data_Analyst,Senior_level
13,IMTAS,"Washington, DC 20535 (Downtown area)",60000.0,Data_Analyst,Senior_level
14,6k Systems,"Washington, DC",60000.0,Data_Analyst,Senior_level
15,HARKEN DATA INC.,"Washington, DC",60000.0,Data_Analyst,Senior_level
16,George Mason University,"Fairfax, VA",60000.0,Data_Analyst,Senior_level
17,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",60000.0,Data_Analyst,Senior_level
18,Dependable Global Solutions,"Washington, DC 20016 (AU-Tenleytown area)",60000.0,Data_Analyst,Senior_level
19,Archimedes Global,"Alexandria, VA",60000.0,Data_Analyst,Senior_level
20,"Data Systems Analysts, Inc.","Fairfax, VA 22030",60000.0,Data_Analyst,Senior_level
21,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",60000.0,Data_Analyst,Senior_level
22,UDig,"Sterling, VA 20166",60000.0,Data_Analyst,Senior_level
23,Centra Technology,"Washington, DC",60000.0,Data_Analyst,Senior_level
24,Vencore,"McLean, VA",60000.0,Data_Analyst,Senior_level
25,IMTAS,"Washington, DC 20001 (Shaw area)",60000.0,Data_Analyst,Senior_level
26,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
27,Garud Technology Services Inc.,"Washington, DC",60000.0,Data_Analyst,Senior_level
28,Information Innovators Inc.,"Washington, DC",60000.0,Data_Analyst,Senior_level
29,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,phia,"Arlington, VA",60000.0,Data_Analyst,Senior_level
76,EXCELLENCE CONSULTING,"Columbia, MD",60000.0,Data_Analyst,Senior_level
77,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
78,The Aerospace Corporation,"Crystal City, VA",60000.0,Data_Analyst,Senior_level
79,"Insight Technology Solutions, Inc.","Washington, DC",60000.0,Data_Analyst,Senior_level
80,"Sylver Rain Consulting, llc","Washington, DC 20004 (Downtown area)",60000.0,Data_Analyst,Senior_level
81,IntelliWare Systems,"Washington, DC",60000.0,Data_Analyst,Senior_level
82,xentity corporation,"Washington, DC",60000.0,Data_Analyst,Senior_level
83,Exelon,"Washington, DC",60000.0,Data_Analyst,Senior_level
84,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
85,Leidos,"Washington, DC",60000.0,Data_Analyst,Senior_level
86,Pearson,"Washington, DC 20036 (Downtown area)",60000.0,Data_Analyst,Senior_level
87,"DELTA Resources, Inc.","Washington, DC",60000.0,Data_Analyst,Senior_level
88,Ventera,"Washington, DC",60000.0,Data_Analyst,Senior_level
89,ALQIMI,"Washington, DC",60000.0,Data_Analyst,Senior_level
90,Freddie Mac,"McLean, VA",60000.0,Data_Analyst,Senior_level
91,Booz Allen Hamilton,"Washington, DC",60000.0,Data_Analyst,Senior_level
92,"GID Solutions, LLC","Quantico, VA",60000.0,Data_Analyst,Senior_level
93,"Concord Crossroads, LLC","Washington, DC",60000.0,Data_Analyst,Senior_level
94,Powertek Corporation,"Chantilly, VA",60000.0,Data_Analyst,Senior_level
95,The MASY Group,"Washington, DC",60000.0,Data_Analyst,Senior_level
96,2U,"Landover, MD",60000.0,Data_Analyst,Senior_level
97,The Johns Hopkins Applied Physics Labo...,"Laurel, MD",60000.0,Data_Analyst,Senior_level
98,"DELTA Resources, Inc.","Washington, DC",60000.0,Data_Analyst,Senior_level
99,General Dynamics Information Technology,"California, MD",60000.0,Data_Analyst,Senior_level
100,CompuGain Solutions,"McLean, VA",60000.0,Data_Analyst,Senior_level
101,"Global Solutions Network, Inc.","Washington, DC",60000.0,Data_Analyst,Senior_level
102,Sonecon LLC,"Washington, DC 20004 (Downtown area)",60000.0,Data_Analyst,Senior_level
103,Salient CRGT,"Washington, DC",60000.0,Data_Analyst,Senior_level
104,Wyle Laboratories,"Anacostia, DC",60000.0,Data_Analyst,Senior_level

## Data_Analyst_DC_70_entry

In [94]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=Washington,+DC&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_70_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_70_entry

,Company_name,Location,Salary,Title,Experience
0,GEICO,"Chevy Chase, MD",70000.0,Data_Analyst,Entry_level
1,"The Upside Travel Company, LLC","Washington, DC",70000.0,Data_Analyst,Entry_level
2,Predictive Science,United States,70000.0,Data_Analyst,Entry_level
3,Cipher3,"Washington, DC",70000.0,Data_Analyst,Entry_level
4,"Interfolio, Inc","Washington, DC 20036 (Downtown area)",70000.0,Data_Analyst,Entry_level
5,JLL,"Washington, DC",70000.0,Data_Analyst,Entry_level
6,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Entry_level
7,Grant Thornton,"Washington, DC 20036 (Downtown area)",70000.0,Data_Analyst,Entry_level
8,FAAZ Consulting LLC,"Washington, DC",70000.0,Data_Analyst,Entry_level
9,Smithsonian Institution,"Washington, DC",70000.0,Data_Analyst,Entry_level
10,Booz Allen Hamilton,"Alexandria, VA",70000.0,Data_Analyst,Entry_level
11,Booz Allen Hamilton,"McLean, VA",70000.0,Data_Analyst,Entry_level
12,Advanced Software Systems,"Arlington, VA",70000.0,Data_Analyst,Entry_level
13,Booz Allen Hamilton,"Silver Spring, MD",70000.0,Data_Analyst,Entry_level
14,US News & World Report,"Washington, DC 20007 (Georgetown area)",70000.0,Data_Analyst,Entry_level
15,AER,"College Park, MD",70000.0,Data_Analyst,Entry_level
16,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Entry_level
17,GEICO,"Chevy Chase, MD",70000.0,Data_Analyst,Entry_level
18,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Entry_level
19,DISYS,"McLean, VA",70000.0,Data_Analyst,Entry_level
20,Korn Ferry/Futurestep,"Washington, DC",70000.0,Data_Analyst,Entry_level
21,Accenture,"Rosslyn, VA",70000.0,Data_Analyst,Entry_level
22,Insequence Inc.,"Herndon, VA 20171",70000.0,Data_Analyst,Entry_level
23,Booz Allen Hamilton,"McLean, VA",70000.0,Data_Analyst,Entry_level
24,Wellcare,"Baltimore, MD",70000.0,Data_Analyst,Entry_level
25,Kavaliro,"Washington, DC",70000.0,Data_Analyst,Entry_level
26,U.S. Department of Labor,"Washington, DC",70000.0,Data_Analyst,Entry_level
27,Mitre Corporation,"McLean, VA",70000.0,Data_Analyst,Entry_level
28,GEICO,"Chevy Chase, MD",70000.0,Data_Analyst,Entry_level
29,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Entry_level
...,...,...,...,...,...
75,Harris Corporation,"Annapolis Junction, MD 20701",70000.0,Data_Analyst,Entry_level
76,"LS Technologies, LLC","Washington, DC",70000.0,Data_Analyst,Entry_level
77,"GreenZone Solutions, Inc.","Washington, DC 20001 (Shaw area)",70000.0,Data_Analyst,Entry_level
78,Olsen Palmer LLC,"Washington, DC 20036 (Downtown area)",70000.0,Data_Analyst,Entry_level
79,Managed Care Advisors,"Bethesda, MD 20814",70000.0,Data_Analyst,Entry_level
80,Centra Technology,"Washington, DC",70000.0,Data_Analyst,Entry_level
81,The Buffalo Group,"Washington, DC",70000.0,Data_Analyst,Entry_level
82,Strategic IT Staffing,"Washington, DC",70000.0,Data_Analyst,Entry_level
83,GEICO,"Chevy Chase, MD",70000.0,Data_Analyst,Entry_level
84,"Sotera Defense Solutions, Inc.","Washington, DC",70000.0,Data_Analyst,Entry_level
85,"Tanager, Inc.","Arlington, VA",70000.0,Data_Analyst,Entry_level
86,"Ajanta Consulting, LLC","Washington, DC",70000.0,Data_Analyst,Entry_level
87,Deloitte,"Washington, DC",70000.0,Data_Analyst,Entry_level
88,Quiet Professionals LLC,"Washington, DC",70000.0,Data_Analyst,Entry_level
89,SyApps LLC,"Washington, DC",70000.0,Data_Analyst,Entry_level
90,Engility Corporation,"Washington, DC 20376 (Brentwood area)",70000.0,Data_Analyst,Entry_level
91,Healthy Directions,"Bethesda, MD",70000.0,Data_Analyst,Entry_level
92,"Integral Consulting Services, Inc.","Rockville, MD",70000.0,Data_Analyst,Entry_level
93,Able Forces,"Alexandria, VA",70000.0,Data_Analyst,Entry_level
94,Jobspring Partners,"Washington, DC 20005 (Logan Circle area)",70000.0,Data_Analyst,Entry_level
95,Exelon,"Baltimore, MD 21223 (West Baltimore area)",70000.0,Data_Analyst,Entry_level
96,U.S. Department of Labor,"Washington, DC",70000.0,Data_Analyst,Entry_level
97,CACI,"Washington, DC 20001 (Shaw area)",70000.0,Data_Analyst,Entry_level
98,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Entry_level
99,IBM Kenexa,"Washington, DC",70000.0,Data_Analyst,Entry_level
100,"Ian, Evan & Alexander Corporation","Washington, DC 20037 (Foggy Bottom area)",70000.0,Data_Analyst,Entry_level
101,Oak Ridge Associated Universities,"Washington, DC",70000.0,Data_Analyst,Entry_level
102,BAE Systems,"Washington, DC",70000.0,Data_Analyst,Entry_level
103,Datalogic Solutions Inc,"Chantilly, VA",70000.0,Data_Analyst,Entry_level
104,Evolent Health,"Arlington, VA 22203",70000.0,Data_Analyst,Entry_level

## Data_Analyst_DC_70_mid

In [95]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=Washington,+DC&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_70_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_70_mid

,Company_name,Location,Salary,Title,Experience
0,Bay State,"Washington, DC",70000.0,Data_Analyst,Mid_level
1,OmniSolve Inc,"Washington, DC",70000.0,Data_Analyst,Mid_level
2,Salient CRGT,"Washington, DC",70000.0,Data_Analyst,Mid_level
3,Compumatics Group,"New Carrollton, MD",70000.0,Data_Analyst,Mid_level
4,The World Bank,"Washington, DC",70000.0,Data_Analyst,Mid_level
5,Dixon Hughes Goodman LLP,"Washington, DC 20016 (AU-Tenleytown area)",70000.0,Data_Analyst,Mid_level
6,DIT Inc,"Washington, DC",70000.0,Data_Analyst,Mid_level
7,Inforeem,"Washington, DC",70000.0,Data_Analyst,Mid_level
8,BCT Partners,"Washington, DC",70000.0,Data_Analyst,Mid_level
9,CAVA,"Washington, DC 20009 (U Street Corridor area)",70000.0,Data_Analyst,Mid_level
10,Adept Solutions,"Washington, DC",70000.0,Data_Analyst,Mid_level
11,"The Center for Organizational Excellence, ...","Washington, DC",70000.0,Data_Analyst,Mid_level
12,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Mid_level
13,American Institutes for Research,"Washington, DC",70000.0,Data_Analyst,Mid_level
14,Legal Services Corporation,"Washington, DC",70000.0,Data_Analyst,Mid_level
15,Excella Consulting,"Washington, DC 20006 (Foggy Bottom area)",70000.0,Data_Analyst,Mid_level
16,Cystic Fibrosis Foundation,"Bethesda, MD 20814",70000.0,Data_Analyst,Mid_level
17,Salient CRGT,"Washington, DC",70000.0,Data_Analyst,Mid_level
18,CRGT Inc.,"Washington, DC",70000.0,Data_Analyst,Mid_level
19,Federal Reserve Board of Governors,"Washington, DC",70000.0,Data_Analyst,Mid_level
20,Booz Allen Hamilton,"Quantico, VA",70000.0,Data_Analyst,Mid_level
21,Dixon Hughes Goodman LLP,"McLean, VA 22102",70000.0,Data_Analyst,Mid_level
22,PCORI,"Washington, DC",70000.0,Data_Analyst,Mid_level
23,"Orbis, Inc.","Washington, DC",70000.0,Data_Analyst,Mid_level
24,Insignia Technology Services,"Washington, DC 20536 (Mount Vernon Square area)",70000.0,Data_Analyst,Mid_level
25,Booz Allen Hamilton,"McLean, VA",70000.0,Data_Analyst,Mid_level
26,Booz Allen Hamilton,"College Park, MD 20740",70000.0,Data_Analyst,Mid_level
27,ICF International,"Fairfax, VA",70000.0,Data_Analyst,Mid_level
28,Butler America Career Portal,"Ashburn, VA 20147",70000.0,Data_Analyst,Mid_level
29,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Mid_level
...,...,...,...,...,...
75,Citizant,"Washington, DC",70000.0,Data_Analyst,Mid_level
76,"Buchanan & Edwards, Inc.","Washington, DC",70000.0,Data_Analyst,Mid_level
77,Salient CRGT,"Arlington, VA",70000.0,Data_Analyst,Mid_level
78,Experis,"Washington, DC 20003 (Capitol Hill area)",70000.0,Data_Analyst,Mid_level
79,NTT DATA Services,"Ashburn, VA",70000.0,Data_Analyst,Mid_level
80,The World Bank,"Washington, DC",70000.0,Data_Analyst,Mid_level
81,Johns Hopkins Hospital/Johns Hopkins H...,"Baltimore, MD",70000.0,Data_Analyst,Mid_level
82,FHI 360,"Washington, DC 20009 (U Street Corridor area)",70000.0,Data_Analyst,Mid_level
83,Booz Allen Hamilton,"Alexandria, VA",70000.0,Data_Analyst,Mid_level
84,ASTA CRS INC.,"Tysons Corner, VA",70000.0,Data_Analyst,Mid_level
85,ABS Consulting,"Arlington, VA",70000.0,Data_Analyst,Mid_level
86,"DB Healthcare, Inc.","Washington, DC",70000.0,Data_Analyst,Mid_level
87,Inovalon,"Bowie, MD 20715",70000.0,Data_Analyst,Mid_level
88,Teracore,"Washington, DC",70000.0,Data_Analyst,Mid_level
89,"Noblis NSP, LLC","Washington, DC",70000.0,Data_Analyst,Mid_level
90,Noblis,"Washington, DC",70000.0,Data_Analyst,Mid_level
91,Office of the Chief Financial Officer (OCFO),"Washington, DC",70000.0,Data_Analyst,Mid_level
92,OmniSolve Inc,"Washington, DC",70000.0,Data_Analyst,Mid_level
93,Ankura Consulting Group,"Washington, DC 20036 (Downtown area)",70000.0,Data_Analyst,Mid_level
94,Engility Corporation,"McLean, VA 22101",70000.0,Data_Analyst,Mid_level
95,Visa,"Ashburn, VA",70000.0,Data_Analyst,Mid_level
96,Vencore,"McLean, VA",70000.0,Data_Analyst,Mid_level
97,ByteCubed,"Arlington, VA",70000.0,Data_Analyst,Mid_level
98,"AVER, LLC","Linthicum Heights, MD 21090",70000.0,Data_Analyst,Mid_level
99,Common Securitization Solutions,"Bethesda, MD",70000.0,Data_Analyst,Mid_level
100,Knight Point Systems,"Washington, DC",70000.0,Data_Analyst,Mid_level
101,Freddie Mac,"McLean, VA",70000.0,Data_Analyst,Mid_level
102,MLT Systems,"Arlington, VA",70000.0,Data_Analyst,Mid_level
103,Net ESolutions Corporation (NETE),"Rockville, MD",70000.0,Data_Analyst,Mid_level
104,Unisys,"Reston, VA",70000.0,Data_Analyst,Mid_level

## Data_Analyst_DC_70_senior

In [96]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=Washington,+DC&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_70_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_70_senior

,Company_name,Location,Salary,Title,Experience
0,Deloitte,"Arlington, VA 22209",70000.0,Data_Analyst,Senior_level
1,Salient CRGT,"Washington, DC",70000.0,Data_Analyst,Senior_level
2,General Dynamics Information Technology,"Springfield, VA",70000.0,Data_Analyst,Senior_level
3,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Senior_level
4,DataNet Systems Corporation,"Washington, DC",70000.0,Data_Analyst,Senior_level
5,"Group Benefit Services, Inc.","Cockeysville, MD 21030",70000.0,Data_Analyst,Senior_level
6,ANSER,"Arlington, VA 22206 (Fairlington-Shirlington a...",70000.0,Data_Analyst,Senior_level
7,General Dynamics Information Technology,"Towson, MD",70000.0,Data_Analyst,Senior_level
8,Indev,"Washington, DC",70000.0,Data_Analyst,Senior_level
9,PricewaterhouseCoopers LLC,"Washington, DC 20001 (Shaw area)",70000.0,Data_Analyst,Senior_level
10,6k Systems,"Washington, DC",70000.0,Data_Analyst,Senior_level
11,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",70000.0,Data_Analyst,Senior_level
12,Archimedes Global,"Alexandria, VA",70000.0,Data_Analyst,Senior_level
13,IMTAS,"Washington, DC 20535 (Downtown area)",70000.0,Data_Analyst,Senior_level
14,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",70000.0,Data_Analyst,Senior_level
15,UDig,"Sterling, VA 20166",70000.0,Data_Analyst,Senior_level
16,"Data Systems Analysts, Inc.","Fairfax, VA 22030",70000.0,Data_Analyst,Senior_level
17,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",70000.0,Data_Analyst,Senior_level
18,Vencore,"McLean, VA",70000.0,Data_Analyst,Senior_level
19,HARKEN DATA INC.,"Washington, DC",70000.0,Data_Analyst,Senior_level
20,Garud Technology Services Inc.,"Washington, DC",70000.0,Data_Analyst,Senior_level
21,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",70000.0,Data_Analyst,Senior_level
22,Dependable Global Solutions,"Washington, DC 20016 (AU-Tenleytown area)",70000.0,Data_Analyst,Senior_level
23,IMTAS,"Washington, DC 20001 (Shaw area)",70000.0,Data_Analyst,Senior_level
24,Information Innovators Inc.,"Washington, DC",70000.0,Data_Analyst,Senior_level
25,"Universal Strategy Group, Inc (USGI)","Washington, DC 20535 (Downtown area)",70000.0,Data_Analyst,Senior_level
26,SC3,"Washington, DC",70000.0,Data_Analyst,Senior_level
27,Centra Technology,"Washington, DC",70000.0,Data_Analyst,Senior_level
28,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Senior_level
29,Leidos,"McLean, VA",70000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Ventera,"Washington, DC",70000.0,Data_Analyst,Senior_level
76,Sayres and Associates,"Washington, DC",70000.0,Data_Analyst,Senior_level
77,"Goldbelt, Inc.","Washington, DC",70000.0,Data_Analyst,Senior_level
78,"Sylver Rain Consulting, llc","Washington, DC 20004 (Downtown area)",70000.0,Data_Analyst,Senior_level
79,"Insight Technology Solutions, Inc.","Washington, DC",70000.0,Data_Analyst,Senior_level
80,The Johns Hopkins Applied Physics Labo...,"Laurel, MD",70000.0,Data_Analyst,Senior_level
81,ECS Federal LLC,"Arlington, VA",70000.0,Data_Analyst,Senior_level
82,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Senior_level
83,xentity corporation,"Washington, DC",70000.0,Data_Analyst,Senior_level
84,Freddie Mac,"McLean, VA",70000.0,Data_Analyst,Senior_level
85,Exelon,"Washington, DC",70000.0,Data_Analyst,Senior_level
86,"GID Solutions, LLC","Quantico, VA",70000.0,Data_Analyst,Senior_level
87,"Global Solutions Network, Inc.","Washington, DC",70000.0,Data_Analyst,Senior_level
88,2U,"Landover, MD",70000.0,Data_Analyst,Senior_level
89,Pearson,"Washington, DC 20036 (Downtown area)",70000.0,Data_Analyst,Senior_level
90,"DELTA Resources, Inc.","Washington, DC",70000.0,Data_Analyst,Senior_level
91,"Concord Crossroads, LLC","Washington, DC",70000.0,Data_Analyst,Senior_level
92,Applied Communication Sciences,"College Park, MD",70000.0,Data_Analyst,Senior_level
93,Leidos,"Washington, DC",70000.0,Data_Analyst,Senior_level
94,Sonecon LLC,"Washington, DC 20004 (Downtown area)",70000.0,Data_Analyst,Senior_level
95,Abacus Technology Corporation,"Washington, DC",70000.0,Data_Analyst,Senior_level
96,TAKE ENTERPRISE SERVICE INC,"Baltimore, MD",70000.0,Data_Analyst,Senior_level
97,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Senior_level
98,The MASY Group,"Washington, DC",70000.0,Data_Analyst,Senior_level
99,Booz Allen Hamilton,"Washington, DC",70000.0,Data_Analyst,Senior_level
100,"DELTA Resources, Inc.","Washington, DC",70000.0,Data_Analyst,Senior_level
101,Booz Allen Hamilton,"McLean, VA",70000.0,Data_Analyst,Senior_level
102,Booz Allen Hamilton,"Fort Meade, MD",70000.0,Data_Analyst,Senior_level
103,General Dynamics Information Technology,"Washington, DC",70000.0,Data_Analyst,Senior_level
104,Wyle Laboratories,"Anacostia, DC",70000.0,Data_Analyst,Senior_level

## extra

In [97]:
df = pd.DataFrame({'Date': ['somedate', 'somedate'],
                   'location': ['united_kingdom_london', 'united_state_newyork'],
                   'occurence': [5, 5]})

In [98]:
df

       Date               location  occurence
0  somedate  united_kingdom_london          5
1  somedate   united_state_newyork          5

In [99]:
df['Country'] = df['location'].str.rpartition('_')[0].str.replace("_", " ")
df['City']    = df['location'].str.rpartition('_')[2]
df[['Date','Country', 'City', 'occurence']]

       Date         Country     City  occurence
0  somedate  united kingdom   london          5
1  somedate    united state  newyork          5

## Data_Analyst_DC_75_entry

In [100]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=Washington,+DC&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_75_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_75_entry

,Company_name,Location,Salary,Title,Experience
0,GEICO,"Chevy Chase, MD",75000.0,Data_Analyst,Entry_level
1,"The Upside Travel Company, LLC","Washington, DC",75000.0,Data_Analyst,Entry_level
2,Datalogic Solutions Inc,"Chantilly, VA",75000.0,Data_Analyst,Entry_level
3,Cipher3,"Washington, DC",75000.0,Data_Analyst,Entry_level
4,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
5,FAAZ Consulting LLC,"Washington, DC",75000.0,Data_Analyst,Entry_level
6,Booz Allen Hamilton,"Alexandria, VA",75000.0,Data_Analyst,Entry_level
7,Accenture,"Rosslyn, VA",75000.0,Data_Analyst,Entry_level
8,Booz Allen Hamilton,"McLean, VA",75000.0,Data_Analyst,Entry_level
9,Advanced Software Systems,"Arlington, VA",75000.0,Data_Analyst,Entry_level
10,Booz Allen Hamilton,"Silver Spring, MD",75000.0,Data_Analyst,Entry_level
11,US News & World Report,"Washington, DC 20007 (Georgetown area)",75000.0,Data_Analyst,Entry_level
12,AER,"College Park, MD",75000.0,Data_Analyst,Entry_level
13,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
14,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
15,DISYS,"McLean, VA",75000.0,Data_Analyst,Entry_level
16,Reveille Group,"Washington, DC",75000.0,Data_Analyst,Entry_level
17,Korn Ferry/Futurestep,"Washington, DC",75000.0,Data_Analyst,Entry_level
18,Insequence Inc.,"Herndon, VA 20171",75000.0,Data_Analyst,Entry_level
19,Booz Allen Hamilton,"McLean, VA",75000.0,Data_Analyst,Entry_level
20,Wellcare,"Baltimore, MD",75000.0,Data_Analyst,Entry_level
21,eAcuity,"Washington, DC",75000.0,Data_Analyst,Entry_level
22,U.S. Department of Labor,"Washington, DC",75000.0,Data_Analyst,Entry_level
23,GEICO,"Chevy Chase, MD",75000.0,Data_Analyst,Entry_level
24,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
25,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
26,Novetta,"Crystal City, VA",75000.0,Data_Analyst,Entry_level
27,ASTA CRS INC.,"Falls Church, VA",75000.0,Data_Analyst,Entry_level
28,Evolent Health,"Arlington, VA 22203 (Bluemont area)",75000.0,Data_Analyst,Entry_level
29,Vox Media,"Washington, DC",75000.0,Data_Analyst,Entry_level
...,...,...,...,...,...
75,kCura Corporation,"Reston, VA",75000.0,Data_Analyst,Entry_level
76,"Ian, Evan & Alexander Corporation","Washington, DC 20037 (Foggy Bottom area)",75000.0,Data_Analyst,Entry_level
77,Synchronoss,"Reston, VA",75000.0,Data_Analyst,Entry_level
78,"Synchronoss Technologies, Inc.","Reston, VA",75000.0,Data_Analyst,Entry_level
79,LongView International Technology Solution...,"Washington, DC",75000.0,Data_Analyst,Entry_level
80,AlixPartners,"Washington, DC",75000.0,Data_Analyst,Entry_level
81,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Entry_level
82,Boecore,"Arlington, VA 22201 (Lyon Village area)",75000.0,Data_Analyst,Entry_level
83,Wyle Laboratories,"Arlington, VA 22202 (Aurora Highlands area)",75000.0,Data_Analyst,Entry_level
84,Computing Concepts Inc.,"Baltimore, MD 21230 (West Baltimore area)",75000.0,Data_Analyst,Entry_level
85,Institute for Defense Analyses,"Alexandria, VA 22311 (Alexandria Wrest area)",75000.0,Data_Analyst,Entry_level
86,Grant Thornton,"Alexandria, VA 22314 (Southwest Quadrant area)",75000.0,Data_Analyst,Entry_level
87,Blue Canopy,"Arlington, VA",75000.0,Data_Analyst,Entry_level
88,"Attain, LLC","Washington, DC",75000.0,Data_Analyst,Entry_level
89,SAIC,"McLean, VA",75000.0,Data_Analyst,Entry_level
90,3M,"Silver Spring, MD",75000.0,Data_Analyst,Entry_level
91,Hilton Corporate,"McLean, VA",75000.0,Data_Analyst,Entry_level
92,absccareers,"Fort Belvoir, VA",75000.0,Data_Analyst,Entry_level
93,Booz Allen Hamilton,"Rockville, MD",75000.0,Data_Analyst,Entry_level
94,GEICO,"Washington, DC",75000.0,Data_Analyst,Entry_level
95,"ThreatConnect, Inc.","Arlington, VA",75000.0,Data_Analyst,Entry_level
96,SRL TotalSource LLC,"Washington, DC",75000.0,Data_Analyst,Entry_level
97,CSRA,"Arlington, VA",75000.0,Data_Analyst,Entry_level
98,"Quantum Research International, Inc.","Arlington, VA 22209 (Radnor-Ft Myer Heights area)",75000.0,Data_Analyst,Entry_level
99,IBM Kenexa,"Washington, DC",75000.0,Data_Analyst,Entry_level
100,Booz Allen Hamilton,"Fort Meade, MD",75000.0,Data_Analyst,Entry_level
101,CSRA,"Chantilly, VA",75000.0,Data_Analyst,Entry_level
102,Engility Corporation,"Bethesda, MD 20892",75000.0,Data_Analyst,Entry_level
103,Predictive Science,United States,75000.0,Data_Analyst,Entry_level
104,Evolent Health,"Arlington, VA 22203",75000.0,Data_Analyst,Entry_level

## Data_Analyst_DC_75_mid

In [101]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=Washington,+DC&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_75_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_75_mid

,Company_name,Location,Salary,Title,Experience
0,Unisys,"Reston, VA",75000.0,Data_Analyst,Mid_level
1,Salient CRGT,"Washington, DC",75000.0,Data_Analyst,Mid_level
2,Aderas,"Reston, VA 20191",75000.0,Data_Analyst,Mid_level
3,The World Bank,"Washington, DC",75000.0,Data_Analyst,Mid_level
4,Compumatics Group,"New Carrollton, MD",75000.0,Data_Analyst,Mid_level
5,DIT Inc,"Washington, DC",75000.0,Data_Analyst,Mid_level
6,Inforeem,"Washington, DC",75000.0,Data_Analyst,Mid_level
7,BCT Partners,"Washington, DC",75000.0,Data_Analyst,Mid_level
8,ICF International,"Fairfax, VA",75000.0,Data_Analyst,Mid_level
9,CAVA,"Washington, DC 20009 (U Street Corridor area)",75000.0,Data_Analyst,Mid_level
10,Booz Allen Hamilton,"Quantico, VA",75000.0,Data_Analyst,Mid_level
11,"The Center for Organizational Excellence, ...","Washington, DC",75000.0,Data_Analyst,Mid_level
12,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Mid_level
13,Legal Services Corporation,"Washington, DC",75000.0,Data_Analyst,Mid_level
14,Excella Consulting,"Washington, DC 20006 (Foggy Bottom area)",75000.0,Data_Analyst,Mid_level
15,Capgemini Government Solutions,"Washington, DC",75000.0,Data_Analyst,Mid_level
16,Dixon Hughes Goodman LLP,"McLean, VA 22102",75000.0,Data_Analyst,Mid_level
17,Dovel Technologies,"McLean, VA",75000.0,Data_Analyst,Mid_level
18,Booz Allen Hamilton,"McLean, VA",75000.0,Data_Analyst,Mid_level
19,Butler America Career Portal,"Ashburn, VA 20147",75000.0,Data_Analyst,Mid_level
20,Federal Reserve Board of Governors,"Washington, DC",75000.0,Data_Analyst,Mid_level
21,"Orbis, Inc.","Washington, DC",75000.0,Data_Analyst,Mid_level
22,Booz Allen Hamilton,"College Park, MD 20740",75000.0,Data_Analyst,Mid_level
23,ASTA CRS INC.,"Tysons Corner, VA",75000.0,Data_Analyst,Mid_level
24,Insignia Technology Services,"Washington, DC 20536 (Mount Vernon Square area)",75000.0,Data_Analyst,Mid_level
25,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Mid_level
26,Engility Corporation,"Washington, DC 20376 (Brentwood area)",75000.0,Data_Analyst,Mid_level
27,The World Bank,"Washington, DC",75000.0,Data_Analyst,Mid_level
28,Abacus Solutions Group,"Cockeysville, MD 21030",75000.0,Data_Analyst,Mid_level
29,"Onyx Government Services, LLC","Washington, DC",75000.0,Data_Analyst,Mid_level
...,...,...,...,...,...
75,Schafer Corporation,"Washington, DC",75000.0,Data_Analyst,Mid_level
76,IBM,"Bethesda, MD 20817",75000.0,Data_Analyst,Mid_level
77,"Integral Consulting Services, Inc.","Arlington, VA",75000.0,Data_Analyst,Mid_level
78,Ankura Consulting Group,"Washington, DC 20036 (Downtown area)",75000.0,Data_Analyst,Mid_level
79,Booz Allen Hamilton,"Alexandria, VA",75000.0,Data_Analyst,Mid_level
80,IBM,"Washington, DC 20005 (Logan Circle area)",75000.0,Data_Analyst,Mid_level
81,IBM,"Washington, DC 20005 (Logan Circle area)",75000.0,Data_Analyst,Mid_level
82,DataNet Systems Corporation,"Washington, DC",75000.0,Data_Analyst,Mid_level
83,TeraThink Corporation,"Arlington, VA 22201 (Lyon Village area)",75000.0,Data_Analyst,Mid_level
84,Booz Allen Hamilton,"Fort Meade, MD",75000.0,Data_Analyst,Mid_level
85,Saint Joseph Health System,"Silver Spring, MD",75000.0,Data_Analyst,Mid_level
86,Vencore,"McLean, VA",75000.0,Data_Analyst,Mid_level
87,American Institutes for Research,"Washington, DC",75000.0,Data_Analyst,Mid_level
88,Technology Service Corporation,"Arlington, VA 22202 (Aurora Highlands area)",75000.0,Data_Analyst,Mid_level
89,Altamira Technologies Corporation,"Springfield, VA",75000.0,Data_Analyst,Mid_level
90,The McKenna Principals Inc,"Herndon, VA",75000.0,Data_Analyst,Mid_level
91,American Society of Clinical Oncology,"Alexandria, VA",75000.0,Data_Analyst,Mid_level
92,"Noblis NSP, LLC","Washington, DC",75000.0,Data_Analyst,Mid_level
93,Noblis,"Washington, DC",75000.0,Data_Analyst,Mid_level
94,"Buchanan & Edwards, Inc.","Washington, DC",75000.0,Data_Analyst,Mid_level
95,Command Consulting Group,"Washington, DC 20036 (Downtown area)",75000.0,Data_Analyst,Mid_level
96,Managed Care Advisors,"Bethesda, MD 20814",75000.0,Data_Analyst,Mid_level
97,The World Bank,"Washington, DC",75000.0,Data_Analyst,Mid_level
98,Visa,"Ashburn, VA",75000.0,Data_Analyst,Mid_level
99,Lexington Solutions Group,"Washington, DC 20032 (Anacostia area)",75000.0,Data_Analyst,Mid_level
100,OmniSolve Inc,"Washington, DC",75000.0,Data_Analyst,Mid_level
101,ByteCubed,"Arlington, VA",75000.0,Data_Analyst,Mid_level
102,Verizon,"Silver Spring, MD 20904",75000.0,Data_Analyst,Mid_level
103,OmniSolve Inc,"Washington, DC",75000.0,Data_Analyst,Mid_level
104,Net ESolutions Corporation (NETE),"Rockville, MD",75000.0,Data_Analyst,Mid_level

## Data_Analyst_DC_75_senior

In [102]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=Washington,+DC&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_75_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_75_senior

,Company_name,Location,Salary,Title,Experience
0,Deloitte,"Arlington, VA 22209",75000.0,Data_Analyst,Senior_level
1,Salient CRGT,"Washington, DC",75000.0,Data_Analyst,Senior_level
2,General Dynamics Information Technology,"Springfield, VA",75000.0,Data_Analyst,Senior_level
3,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Senior_level
4,DataNet Systems Corporation,"Washington, DC",75000.0,Data_Analyst,Senior_level
5,"Group Benefit Services, Inc.","Cockeysville, MD 21030",75000.0,Data_Analyst,Senior_level
6,IMTAS,"Washington, DC 20535 (Downtown area)",75000.0,Data_Analyst,Senior_level
7,ANSER,"Arlington, VA 22206 (Fairlington-Shirlington a...",75000.0,Data_Analyst,Senior_level
8,General Dynamics Information Technology,"Towson, MD",75000.0,Data_Analyst,Senior_level
9,Indev,"Washington, DC",75000.0,Data_Analyst,Senior_level
10,PricewaterhouseCoopers LLC,"Washington, DC 20001 (Shaw area)",75000.0,Data_Analyst,Senior_level
11,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",75000.0,Data_Analyst,Senior_level
12,Archimedes Global,"Alexandria, VA",75000.0,Data_Analyst,Senior_level
13,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",75000.0,Data_Analyst,Senior_level
14,ASRC Federal,"Arlington, VA",75000.0,Data_Analyst,Senior_level
15,UDig,"Sterling, VA 20166",75000.0,Data_Analyst,Senior_level
16,"Data Systems Analysts, Inc.","Fairfax, VA 22030",75000.0,Data_Analyst,Senior_level
17,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",75000.0,Data_Analyst,Senior_level
18,Vencore,"McLean, VA",75000.0,Data_Analyst,Senior_level
19,HARKEN DATA INC.,"Washington, DC",75000.0,Data_Analyst,Senior_level
20,Garud Technology Services Inc.,"Washington, DC",75000.0,Data_Analyst,Senior_level
21,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",75000.0,Data_Analyst,Senior_level
22,Dependable Global Solutions,"Washington, DC 20016 (AU-Tenleytown area)",75000.0,Data_Analyst,Senior_level
23,fhi360,"Washington, DC",75000.0,Data_Analyst,Senior_level
24,IMTAS,"Washington, DC 20001 (Shaw area)",75000.0,Data_Analyst,Senior_level
25,Information Innovators Inc.,"Washington, DC",75000.0,Data_Analyst,Senior_level
26,"Universal Strategy Group, Inc (USGI)","Washington, DC 20535 (Downtown area)",75000.0,Data_Analyst,Senior_level
27,SC3,"Washington, DC",75000.0,Data_Analyst,Senior_level
28,Centra Technology,"Washington, DC",75000.0,Data_Analyst,Senior_level
29,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,The Johns Hopkins Applied Physics Labo...,"Laurel, MD",75000.0,Data_Analyst,Senior_level
76,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Senior_level
77,xentity corporation,"Washington, DC",75000.0,Data_Analyst,Senior_level
78,Freddie Mac,"McLean, VA",75000.0,Data_Analyst,Senior_level
79,"GID Solutions, LLC","Quantico, VA",75000.0,Data_Analyst,Senior_level
80,"Global Solutions Network, Inc.","Washington, DC",75000.0,Data_Analyst,Senior_level
81,2U,"Landover, MD",75000.0,Data_Analyst,Senior_level
82,"DELTA Resources, Inc.","Washington, DC",75000.0,Data_Analyst,Senior_level
83,"Concord Crossroads, LLC","Washington, DC",75000.0,Data_Analyst,Senior_level
84,Applied Communication Sciences,"College Park, MD",75000.0,Data_Analyst,Senior_level
85,Sonecon LLC,"Washington, DC 20004 (Downtown area)",75000.0,Data_Analyst,Senior_level
86,Abacus Technology Corporation,"Washington, DC",75000.0,Data_Analyst,Senior_level
87,TAKE ENTERPRISE SERVICE INC,"Baltimore, MD",75000.0,Data_Analyst,Senior_level
88,The MASY Group,"Washington, DC",75000.0,Data_Analyst,Senior_level
89,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Senior_level
90,"Vector Planning & Services, Inc","Washington, DC",75000.0,Data_Analyst,Senior_level
91,Booz Allen Hamilton,"McLean, VA",75000.0,Data_Analyst,Senior_level
92,Booz Allen Hamilton,"Fort Meade, MD",75000.0,Data_Analyst,Senior_level
93,IntelliWare Systems,"Washington, DC",75000.0,Data_Analyst,Senior_level
94,Sev1Tech,"Washington, DC",75000.0,Data_Analyst,Senior_level
95,Alion Science and Technology,"Washington, DC 20003 (Capitol Hill area)",75000.0,Data_Analyst,Senior_level
96,"Quadrant, Inc.","Silver Spring, MD 20910",75000.0,Data_Analyst,Senior_level
97,Applied Memetics LLC,"Washington, DC",75000.0,Data_Analyst,Senior_level
98,Booz Allen Hamilton,"Washington, DC",75000.0,Data_Analyst,Senior_level
99,SAIC,"Fort Belvoir, VA",75000.0,Data_Analyst,Senior_level
100,"SnagAJob.com, Inc","Arlington, VA 22201 (Lyon Village area)",75000.0,Data_Analyst,Senior_level
101,General Dynamics Information Technology,"Quantico, VA",75000.0,Data_Analyst,Senior_level
102,Maden Technologies,"Washington, DC",75000.0,Data_Analyst,Senior_level
103,General Dynamics Information Technology,"Washington, DC",75000.0,Data_Analyst,Senior_level
104,Wyle Laboratories,"Anacostia, DC",75000.0,Data_Analyst,Senior_level

## Data_Analyst_DC_85_entry

In [103]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=Washington,+DC&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_85_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_85_entry

,Company_name,Location,Salary,Title,Experience
0,Evolent Health,"Arlington, VA 22203",85000.0,Data_Analyst,Entry_level
1,Veris Group,"Washington, DC",85000.0,Data_Analyst,Entry_level
2,Datalogic Solutions Inc,"Chantilly, VA",85000.0,Data_Analyst,Entry_level
3,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
4,FAAZ Consulting LLC,"Washington, DC",85000.0,Data_Analyst,Entry_level
5,Booz Allen Hamilton,"Alexandria, VA",85000.0,Data_Analyst,Entry_level
6,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
7,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
8,DISYS,"McLean, VA",85000.0,Data_Analyst,Entry_level
9,Boecore,"Arlington, VA 22201 (Lyon Village area)",85000.0,Data_Analyst,Entry_level
10,Accenture,"Rosslyn, VA",85000.0,Data_Analyst,Entry_level
11,Insequence Inc.,"Herndon, VA 20171",85000.0,Data_Analyst,Entry_level
12,Booz Allen Hamilton,"McLean, VA",85000.0,Data_Analyst,Entry_level
13,eAcuity,"Washington, DC",85000.0,Data_Analyst,Entry_level
14,U.S. Department of Labor,"Washington, DC",85000.0,Data_Analyst,Entry_level
15,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
16,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
17,Vox Media,"Washington, DC",85000.0,Data_Analyst,Entry_level
18,Deloitte,"Arlington, VA 22209 (Radnor-Ft Myer Heights area)",85000.0,Data_Analyst,Entry_level
19,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
20,Booz Allen Hamilton,"Alexandria, VA",85000.0,Data_Analyst,Entry_level
21,Booz Allen Hamilton,"McLean, VA",85000.0,Data_Analyst,Entry_level
22,"Integral Consulting Services, Inc.","Rockville, MD",85000.0,Data_Analyst,Entry_level
23,U.S. Department of Labor,"Washington, DC",85000.0,Data_Analyst,Entry_level
24,Grant Thornton,"Washington, DC 20036 (Downtown area)",85000.0,Data_Analyst,Entry_level
25,Gryphon Scientific,"Takoma Park, MD",85000.0,Data_Analyst,Entry_level
26,Atlas Research,"Washington, DC 20005 (Logan Circle area)",85000.0,Data_Analyst,Entry_level
27,Booz Allen Hamilton,"Fort Meade, MD",85000.0,Data_Analyst,Entry_level
28,Trinity Global Consulting,"Springfield, VA",85000.0,Data_Analyst,Entry_level
29,REDHORSE CORPORATION,"Arlington, VA 22202 (Aurora Highlands area)",85000.0,Data_Analyst,Entry_level
...,...,...,...,...,...
75,Omnitek Consulting,"Gaithersburg, MD",85000.0,Data_Analyst,Entry_level
76,Prism Inc.,"Vienna, VA",85000.0,Data_Analyst,Entry_level
77,Alvarez & Marsal,"Washington, DC 20004 (Downtown area)",85000.0,Data_Analyst,Entry_level
78,"Storage Strategies, Inc.","Springfield, VA",85000.0,Data_Analyst,Entry_level
79,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Entry_level
80,Mitre Corporation,"McLean, VA",85000.0,Data_Analyst,Entry_level
81,SC3,"Washington, DC",85000.0,Data_Analyst,Entry_level
82,Veris Group,"Washington, DC",85000.0,Data_Analyst,Entry_level
83,Transportation Security Administration,"Arlington, VA",85000.0,Data_Analyst,Entry_level
84,Booz Allen Hamilton,"Quantico, VA",85000.0,Data_Analyst,Entry_level
85,The Tauri Group,"Alexandria, VA",85000.0,Data_Analyst,Entry_level
86,IBM Kenexa,"Bethesda, MD",85000.0,Data_Analyst,Entry_level
87,ROI Checker,"Vienna, VA 22180",85000.0,Data_Analyst,Entry_level
88,"Arlington County, VA","Arlington, VA",85000.0,Data_Analyst,Entry_level
89,CSRA,"Arlington, VA",85000.0,Data_Analyst,Entry_level
90,Arc Aspicio,"Arlington, VA 22207 (Yorktown area)",85000.0,Data_Analyst,Entry_level
91,Sayres and Associates,"Washington, DC",85000.0,Data_Analyst,Entry_level
92,Veteran Staffing Network of Easter Seals,"McLean, VA",85000.0,Data_Analyst,Entry_level
93,Evolent Health,"Arlington, VA 22203 (Bluemont area)",85000.0,Data_Analyst,Entry_level
94,USM,"Washington, DC",85000.0,Data_Analyst,Entry_level
95,Systems & Technology Research,"Arlington, VA 22203 (Bluemont area)",85000.0,Data_Analyst,Entry_level
96,Tandler Recruiting,"Tysons, VA",85000.0,Data_Analyst,Entry_level
97,"Cameo Consulting Group, LLC","Washington, DC",85000.0,Data_Analyst,Entry_level
98,Sysmatics Inc.,"Arlington, VA",85000.0,Data_Analyst,Entry_level
99,Hewlett Packard Enterprise,"Herndon, VA",85000.0,Data_Analyst,Entry_level
100,Knight Federal Solutions,"Washington, DC",85000.0,Data_Analyst,Entry_level
101,Synergy BIS,"Arlington, VA 22209 (Radnor-Ft Myer Heights area)",85000.0,Data_Analyst,Entry_level
102,Tunnell Consulting,"Washington, DC 20009 (U Street Corridor area)",85000.0,Data_Analyst,Entry_level
103,Amazon Corporate LLC,United States,85000.0,Data_Analyst,Entry_level
104,Predictive Science,United States,85000.0,Data_Analyst,Entry_level

## Data_Analyst_DC_85_mid

In [104]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=Washington,+DC&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_85_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_85_mid

,Company_name,Location,Salary,Title,Experience
0,OmniSolve Inc,"Washington, DC",85000.0,Data_Analyst,Mid_level
1,Aderas,"Reston, VA 20191",85000.0,Data_Analyst,Mid_level
2,"FTI Consulting, Inc.","McLean, VA",85000.0,Data_Analyst,Mid_level
3,The World Bank,"Washington, DC",85000.0,Data_Analyst,Mid_level
4,Compumatics Group,"New Carrollton, MD",85000.0,Data_Analyst,Mid_level
5,Booz Allen Hamilton,"Quantico, VA",85000.0,Data_Analyst,Mid_level
6,Inforeem,"Washington, DC",85000.0,Data_Analyst,Mid_level
7,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Mid_level
8,Legal Services Corporation,"Washington, DC",85000.0,Data_Analyst,Mid_level
9,Excella Consulting,"Washington, DC 20006 (Foggy Bottom area)",85000.0,Data_Analyst,Mid_level
10,Dixon Hughes Goodman LLP,"McLean, VA 22102",85000.0,Data_Analyst,Mid_level
11,Booz Allen Hamilton,"College Park, MD 20740",85000.0,Data_Analyst,Mid_level
12,Johns Hopkins Hospital/Johns Hopkins H...,"Baltimore, MD",85000.0,Data_Analyst,Mid_level
13,Dovel Technologies,"McLean, VA",85000.0,Data_Analyst,Mid_level
14,Engility Corporation,"Washington, DC 20376 (Brentwood area)",85000.0,Data_Analyst,Mid_level
15,Booz Allen Hamilton,"McLean, VA",85000.0,Data_Analyst,Mid_level
16,The World Bank,"Washington, DC",85000.0,Data_Analyst,Mid_level
17,Booz Allen Hamilton,"College Park, MD 20740",85000.0,Data_Analyst,Mid_level
18,"Onyx Government Services, LLC","Washington, DC",85000.0,Data_Analyst,Mid_level
19,Common Securitization Solutions,"Bethesda, MD",85000.0,Data_Analyst,Mid_level
20,Systems Planning and Analysis,"Alexandria, VA 22311 (Alexandria Wrest area)",85000.0,Data_Analyst,Mid_level
21,"VISUAL SOFT, INC","Washington, DC",85000.0,Data_Analyst,Mid_level
22,Under Armour,"Baltimore, MD",85000.0,Data_Analyst,Mid_level
23,Prometric,"Nottingham, MD",85000.0,Data_Analyst,Mid_level
24,SA Solutions Inc. (SAS),"Lanham, MD",85000.0,Data_Analyst,Mid_level
25,Archimedes Global,"Alexandria, VA",85000.0,Data_Analyst,Mid_level
26,DataNet Systems Corporation,"Washington, DC",85000.0,Data_Analyst,Mid_level
27,Net ESolutions Corporation (NETE),"Rockville, MD",85000.0,Data_Analyst,Mid_level
28,ANALYTICA,"Washington, DC 20036 (Downtown area)",85000.0,Data_Analyst,Mid_level
29,Booz Allen Hamilton,"Herndon, VA",85000.0,Data_Analyst,Mid_level
...,...,...,...,...,...
75,Common Securitization Solutions,"Bethesda, MD",85000.0,Data_Analyst,Mid_level
76,The Johns Hopkins Applied Physics Labo...,"Laurel, MD",85000.0,Data_Analyst,Mid_level
77,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Mid_level
78,Archimedes Global,"Washington, DC",85000.0,Data_Analyst,Mid_level
79,KPMG,"Washington, DC 20036 (Downtown area)",85000.0,Data_Analyst,Mid_level
80,Mitre Corporation,"Washington, DC 20024 (South West area)",85000.0,Data_Analyst,Mid_level
81,IBM,"Washington, DC 20005 (Logan Circle area)",85000.0,Data_Analyst,Mid_level
82,COMPASS,"Washington, DC",85000.0,Data_Analyst,Mid_level
83,Atlas Research,"Washington, DC 20005 (Logan Circle area)",85000.0,Data_Analyst,Mid_level
84,"VISUAL SOFT, INC","Washington, DC",85000.0,Data_Analyst,Mid_level
85,DataRobot,"Washington, DC",85000.0,Data_Analyst,Mid_level
86,IBM Kenexa,"Washington, DC",85000.0,Data_Analyst,Mid_level
87,Aquila Technology,"Springfield, VA",85000.0,Data_Analyst,Mid_level
88,Celestar Corporation,"Bolling AFB, DC",85000.0,Data_Analyst,Mid_level
89,DECISIVE ANALYTICS Corporation,"Alexandria, VA",85000.0,Data_Analyst,Mid_level
90,USM,"Washington, DC",85000.0,Data_Analyst,Mid_level
91,S&P GLOBAL MARKET INTELLIGENCE,"Arlington, VA 22209 (Radnor-Ft Myer Heights area)",85000.0,Data_Analyst,Mid_level
92,"Onyx Government Services, LLC","Washington, DC",85000.0,Data_Analyst,Mid_level
93,Wyle Laboratories,"Arlington, VA 22202 (Aurora Highlands area)",85000.0,Data_Analyst,Mid_level
94,Greater Baltimore Medical Center,"Baltimore, MD 21203 (Old Town area)",85000.0,Data_Analyst,Mid_level
95,Ellucian.,"Fairfax, VA",85000.0,Data_Analyst,Mid_level
96,StraighterLine,"Baltimore, MD",85000.0,Data_Analyst,Mid_level
97,Systems Planning and Analysis,"Alexandria, VA 22311 (Alexandria Wrest area)",85000.0,Data_Analyst,Mid_level
98,Ukpeagvik Iñupiat Corporation/Bowhead Fami...,"Washington, DC",85000.0,Data_Analyst,Mid_level
99,Evolent Health,"Arlington, VA 22203 (Bluemont area)",85000.0,Data_Analyst,Mid_level
100,Evolent Health,"Arlington, VA 22203 (Bluemont area)",85000.0,Data_Analyst,Mid_level
101,TAC Integrated Solutions,"Arlington, VA",85000.0,Data_Analyst,Mid_level
102,General Dynamics Information Technology,"Lanham, MD",85000.0,Data_Analyst,Mid_level
103,Salient CRGT,"Arlington, VA",85000.0,Data_Analyst,Mid_level
104,Net ESolutions Corporation (NETE),"Rockville, MD",85000.0,Data_Analyst,Mid_level

## Data_Analyst_DC_85_senior

In [105]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=Washington,+DC&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_85_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_85_senior

,Company_name,Location,Salary,Title,Experience
0,Wyle Laboratories,"Anacostia, DC",85000.0,Data_Analyst,Senior_level
1,General Dynamics Information Technology,"Washington, DC",85000.0,Data_Analyst,Senior_level
2,General Dynamics Information Technology,"Suitland, MD",85000.0,Data_Analyst,Senior_level
3,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Senior_level
4,DataNet Systems Corporation,"Washington, DC",85000.0,Data_Analyst,Senior_level
5,"Universal Strategy Group, Inc (USGI)","Washington, DC 20535 (Downtown area)",85000.0,Data_Analyst,Senior_level
6,SC3,"Washington, DC",85000.0,Data_Analyst,Senior_level
7,ANSER,"Arlington, VA 22206 (Fairlington-Shirlington a...",85000.0,Data_Analyst,Senior_level
8,Indev,"Washington, DC",85000.0,Data_Analyst,Senior_level
9,IMTAS,"Washington, DC 20535 (Downtown area)",85000.0,Data_Analyst,Senior_level
10,New Beginnings LLC,"Washington, DC 20002 (Capitol Hill area)",85000.0,Data_Analyst,Senior_level
11,"Data Systems Analysts, Inc.","Fairfax, VA 22030",85000.0,Data_Analyst,Senior_level
12,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",85000.0,Data_Analyst,Senior_level
13,Vencore,"McLean, VA",85000.0,Data_Analyst,Senior_level
14,HARKEN DATA INC.,"Washington, DC",85000.0,Data_Analyst,Senior_level
15,Garud Technology Services Inc.,"Washington, DC",85000.0,Data_Analyst,Senior_level
16,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",85000.0,Data_Analyst,Senior_level
17,Dependable Global Solutions,"Washington, DC 20016 (AU-Tenleytown area)",85000.0,Data_Analyst,Senior_level
18,IMTAS,"Washington, DC 20001 (Shaw area)",85000.0,Data_Analyst,Senior_level
19,Information Innovators Inc.,"Washington, DC",85000.0,Data_Analyst,Senior_level
20,Centra Technology,"Washington, DC",85000.0,Data_Analyst,Senior_level
21,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Senior_level
22,"Concord Crossroads, LLC","Washington, DC",85000.0,Data_Analyst,Senior_level
23,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Senior_level
24,ICF International,"Fairfax, VA",85000.0,Data_Analyst,Senior_level
25,Leonie,"Arlington, VA",85000.0,Data_Analyst,Senior_level
26,The MASY Group,"Washington, DC",85000.0,Data_Analyst,Senior_level
27,Prism Inc.,"Vienna, VA",85000.0,Data_Analyst,Senior_level
28,IntelliWare Systems,"Washington, DC",85000.0,Data_Analyst,Senior_level
29,ACI Federal,"Baltimore, MD",85000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Customer Value Partners,"Washington, DC",85000.0,Data_Analyst,Senior_level
76,"Applied Computing Technologies, Inc.","Bluemont, VA",85000.0,Data_Analyst,Senior_level
77,Assertive Professionals,"Springfield, VA 22150",85000.0,Data_Analyst,Senior_level
78,Booz Allen Hamilton,"Quantico, VA",85000.0,Data_Analyst,Senior_level
79,Alqimi,"Washington, DC",85000.0,Data_Analyst,Senior_level
80,Booz Allen Hamilton,"Chantilly, VA 20151",85000.0,Data_Analyst,Senior_level
81,Knowesis Inc.,"Arlington, VA 22201 (Lyon Village area)",85000.0,Data_Analyst,Senior_level
82,Booz Allen Hamilton,"Chantilly, VA 20151",85000.0,Data_Analyst,Senior_level
83,Total Systems Technologies Corporation,"Washington, DC",85000.0,Data_Analyst,Senior_level
84,Raytheon,"McLean, VA",85000.0,Data_Analyst,Senior_level
85,Harris Corporation,"Annapolis Junction, MD 20701",85000.0,Data_Analyst,Senior_level
86,Visa,"Ashburn, VA",85000.0,Data_Analyst,Senior_level
87,Apex IT Services LLC,"Baltimore, MD",85000.0,Data_Analyst,Senior_level
88,Raas Infotek LLC,"Baltimore, MD",85000.0,Data_Analyst,Senior_level
89,GovPEO,"Washington, DC",85000.0,Data_Analyst,Senior_level
90,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Senior_level
91,The Aerospace Corporation,"Arlington, VA 22202 (Aurora Highlands area)",85000.0,Data_Analyst,Senior_level
92,Logistics Support,"Washington, DC 20003 (Capitol Hill area)",85000.0,Data_Analyst,Senior_level
93,"Vector Planning & Services, Inc","Washington, DC",85000.0,Data_Analyst,Senior_level
94,Booz Allen Hamilton,"Washington, DC",85000.0,Data_Analyst,Senior_level
95,Unity Technologies Corporation,"Frederick, MD",85000.0,Data_Analyst,Senior_level
96,Howard Hughes Medical Institute,"Chevy Chase, MD 20815",85000.0,Data_Analyst,Senior_level
97,Booz Allen Hamilton,"McLean, VA",85000.0,Data_Analyst,Senior_level
98,Camris International,"Washington, DC 20004 (Downtown area)",85000.0,Data_Analyst,Senior_level
99,Vox Media,"Washington, DC",85000.0,Data_Analyst,Senior_level
100,Booz Allen Hamilton,"Alexandria, VA",85000.0,Data_Analyst,Senior_level
101,Kearney & Company,"Alexandria, VA 22314 (Southwest Quadrant area)",85000.0,Data_Analyst,Senior_level
102,TCP Stream,"Rosslyn, VA",85000.0,Data_Analyst,Senior_level
103,BlackBerry,"Washington, DC",85000.0,Data_Analyst,Senior_level
104,General Dynamics Information Technology,"Springfield, VA",85000.0,Data_Analyst,Senior_level

## Data_Analyst_DC_100_entry

In [106]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=Washington,+DC&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_100_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_100_entry

,Company_name,Location,Salary,Title,Experience
0,Datalogic Solutions Inc,"Chantilly, VA",100000.0,Data_Analyst,Entry_level
1,Engility Corporation,"Washington, DC 20376",100000.0,Data_Analyst,Entry_level
2,Deloitte,"Arlington, VA 22209",100000.0,Data_Analyst,Entry_level
3,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Entry_level
4,FAAZ Consulting LLC,"Washington, DC",100000.0,Data_Analyst,Entry_level
5,Booz Allen Hamilton,"Alexandria, VA",100000.0,Data_Analyst,Entry_level
6,DISYS,"McLean, VA",100000.0,Data_Analyst,Entry_level
7,Insequence Inc.,"Herndon, VA 20171",100000.0,Data_Analyst,Entry_level
8,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Entry_level
9,Vox Media,"Washington, DC",100000.0,Data_Analyst,Entry_level
10,Booz Allen Hamilton,"McLean, VA",100000.0,Data_Analyst,Entry_level
11,"Integral Consulting Services, Inc.","Rockville, MD",100000.0,Data_Analyst,Entry_level
12,U.S. Department of Labor,"Washington, DC",100000.0,Data_Analyst,Entry_level
13,The Buffalo Group,"Washington, DC",100000.0,Data_Analyst,Entry_level
14,Engility Corporation,"Washington, DC 20376 (Brentwood area)",100000.0,Data_Analyst,Entry_level
15,Jobspring Partners,"Washington, DC 20005 (Logan Circle area)",100000.0,Data_Analyst,Entry_level
16,CACI,"Washington, DC 20001 (Shaw area)",100000.0,Data_Analyst,Entry_level
17,"Ian, Evan & Alexander Corporation","Washington, DC 20037 (Foggy Bottom area)",100000.0,Data_Analyst,Entry_level
18,Computing Concepts Inc.,"Baltimore, MD 21230 (West Baltimore area)",100000.0,Data_Analyst,Entry_level
19,Blue Canopy,"Arlington, VA",100000.0,Data_Analyst,Entry_level
20,SAIC,"McLean, VA",100000.0,Data_Analyst,Entry_level
21,"ThreatConnect, Inc.","Arlington, VA",100000.0,Data_Analyst,Entry_level
22,SRL TotalSource LLC,"Washington, DC",100000.0,Data_Analyst,Entry_level
23,Engility Corporation,"Bethesda, MD 20892",100000.0,Data_Analyst,Entry_level
24,Custom Software Systems Inc.,"Washington, DC 20004 (Downtown area)",100000.0,Data_Analyst,Entry_level
25,Bulletin Intelligence,"Reston, VA 20191",100000.0,Data_Analyst,Entry_level
26,Celerity,"McLean, VA 22102",100000.0,Data_Analyst,Entry_level
27,Bulletin Intelligence,"Reston, VA 20191",100000.0,Data_Analyst,Entry_level
28,OPTOMI LLC,"Dulles, VA",100000.0,Data_Analyst,Entry_level
29,Whiteboard Federal Technologies,"Herndon, VA",100000.0,Data_Analyst,Entry_level
...,...,...,...,...,...
75,Modis,"Gaithersburg, MD 20878",100000.0,Data_Analyst,Entry_level
76,Booz Allen Hamilton,"Fort Meade, MD",100000.0,Data_Analyst,Entry_level
77,DC&M Partners,"Washington, DC 20001 (Shaw area)",100000.0,Data_Analyst,Entry_level
78,"RTGX, Inc.","Beltsville, MD",100000.0,Data_Analyst,Entry_level
79,Selby Jennings,"Alexandria, VA",100000.0,Data_Analyst,Entry_level
80,Ashton Lane Group,"Baltimore, MD",100000.0,Data_Analyst,Entry_level
81,RiskSpan,"Tysons Corner, VA",100000.0,Data_Analyst,Entry_level
82,KEYW Corporation,"Annapolis Junction, MD",100000.0,Data_Analyst,Entry_level
83,Apex Systems Inc,"Woodlawn, MD",100000.0,Data_Analyst,Entry_level
84,Phoenix Operations Group,"Annapolis Junction, MD",100000.0,Data_Analyst,Entry_level
85,"Commonwealth Computer Research, Inc.","Chantilly, VA",100000.0,Data_Analyst,Entry_level
86,Capital One,"Vienna, VA",100000.0,Data_Analyst,Entry_level
87,"Aveshka, Inc.","Arlington, VA 22203 (Bluemont area)",100000.0,Data_Analyst,Entry_level
88,"MedImmune, LLC","Gaithersburg, MD",100000.0,Data_Analyst,Entry_level
89,SAIC,"McLean, VA",100000.0,Data_Analyst,Entry_level
90,"Aveshka, Inc.","McLean, VA",100000.0,Data_Analyst,Entry_level
91,"Sphere of Influence, Inc.","West McLean, VA 22102",100000.0,Data_Analyst,Entry_level
92,Corporate Brokers,"Baltimore, MD",100000.0,Data_Analyst,Entry_level
93,SAIC,"McLean, VA",100000.0,Data_Analyst,Entry_level
94,The Squires Group Inc.,"Greenbelt, MD",100000.0,Data_Analyst,Entry_level
95,IBM Kenexa,"Chantilly, VA",100000.0,Data_Analyst,Entry_level
96,Mesosphere,"Washington, DC",100000.0,Data_Analyst,Entry_level
97,ZP Group,"Washington, DC 20019 (Deanwood area)",100000.0,Data_Analyst,Entry_level
98,Aegis,"McLean, VA 22102",100000.0,Data_Analyst,Entry_level
99,AstraZeneca,"Gaithersburg, MD",100000.0,Data_Analyst,Entry_level
100,Green Key Resources,"Washington, DC",100000.0,Data_Analyst,Entry_level
101,Foundation Staffing,"Silver Springs, MD",100000.0,Data_Analyst,Entry_level
102,Association of Universities for Research i...,"Baltimore, MD",100000.0,Data_Analyst,Entry_level
103,Engility Corporation,"Bethesda, MD 20892",100000.0,Data_Analyst,Entry_level
104,Predictive Science,United States,100000.0,Data_Analyst,Entry_level

## Data_Analyst_DC_100_mid

In [107]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=Washington,+DC&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_100_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_100_mid

,Company_name,Location,Salary,Title,Experience
0,OmniSolve Inc,"Washington, DC",100000.0,Data_Analyst,Mid_level
1,RCM Solutions,"Washington, DC",100000.0,Data_Analyst,Mid_level
2,All Things Considered Staffing (ATC-S),"Washington, DC",100000.0,Data_Analyst,Mid_level
3,The World Bank,"Washington, DC",100000.0,Data_Analyst,Mid_level
4,Compumatics Group,"New Carrollton, MD",100000.0,Data_Analyst,Mid_level
5,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Mid_level
6,Excella Consulting,"Washington, DC 20006 (Foggy Bottom area)",100000.0,Data_Analyst,Mid_level
7,Booz Allen Hamilton,"College Park, MD 20740",100000.0,Data_Analyst,Mid_level
8,Engility Corporation,"Washington, DC 20376 (Brentwood area)",100000.0,Data_Analyst,Mid_level
9,The World Bank,"Washington, DC",100000.0,Data_Analyst,Mid_level
10,Systems Planning and Analysis,"Alexandria, VA 22311 (Alexandria Wrest area)",100000.0,Data_Analyst,Mid_level
11,"VISUAL SOFT, INC","Washington, DC",100000.0,Data_Analyst,Mid_level
12,Karsun Solutions LLC,"Herndon, VA",100000.0,Data_Analyst,Mid_level
13,Archimedes Global,"Alexandria, VA",100000.0,Data_Analyst,Mid_level
14,ASRC Federal,"Alexandria, VA",100000.0,Data_Analyst,Mid_level
15,ANALYTICA,"Washington, DC 20036 (Downtown area)",100000.0,Data_Analyst,Mid_level
16,Booz Allen Hamilton,"Alexandria, VA",100000.0,Data_Analyst,Mid_level
17,Booz Allen Hamilton,"Fort Meade, MD",100000.0,Data_Analyst,Mid_level
18,Vencore,"McLean, VA",100000.0,Data_Analyst,Mid_level
19,Altamira Technologies Corporation,"Springfield, VA",100000.0,Data_Analyst,Mid_level
20,Command Consulting Group,"Washington, DC 20036 (Downtown area)",100000.0,Data_Analyst,Mid_level
21,The World Bank,"Washington, DC",100000.0,Data_Analyst,Mid_level
22,OmniSolve Inc,"Washington, DC",100000.0,Data_Analyst,Mid_level
23,Verizon,"Silver Spring, MD 20904",100000.0,Data_Analyst,Mid_level
24,Booz Allen Hamilton,"McLean, VA",100000.0,Data_Analyst,Mid_level
25,The World Bank Group,"Washington, DC",100000.0,Data_Analyst,Mid_level
26,"Transportation, District Dept","Washington, DC",100000.0,Data_Analyst,Mid_level
27,Booz Allen Hamilton,"Alexandria, VA",100000.0,Data_Analyst,Mid_level
28,Oscar Technology,"Baltimore, MD",100000.0,Data_Analyst,Mid_level
29,Aquila Technology,"Springfield, VA",100000.0,Data_Analyst,Mid_level
...,...,...,...,...,...
75,LongView International Technology Solution...,"Reston, VA",100000.0,Data_Analyst,Mid_level
76,IBM,"Washington, DC 20005 (Logan Circle area)",100000.0,Data_Analyst,Mid_level
77,KPMG,"McLean, VA",100000.0,Data_Analyst,Mid_level
78,Booz Allen Hamilton,"Reston, VA",100000.0,Data_Analyst,Mid_level
79,Booz Allen Hamilton,"Fort Meade, MD",100000.0,Data_Analyst,Mid_level
80,Logistics Management Institute,"Washington, DC",100000.0,Data_Analyst,Mid_level
81,Robert Walters,"Washington, DC",100000.0,Data_Analyst,Mid_level
82,IBM Kenexa,"Washington, DC",100000.0,Data_Analyst,Mid_level
83,Prism Inc.,"Washington, DC",100000.0,Data_Analyst,Mid_level
84,USM,"Washington, DC",100000.0,Data_Analyst,Mid_level
85,KPMG,"Washington, DC 20036 (Downtown area)",100000.0,Data_Analyst,Mid_level
86,T-Rex Corporation,"Greenbelt, MD 20770",100000.0,Data_Analyst,Mid_level
87,Common Securitization Solutions,"Bethesda, MD",100000.0,Data_Analyst,Mid_level
88,Capital One,"McLean, VA",100000.0,Data_Analyst,Mid_level
89,"NCI Information Systems, Inc.","Washington, DC",100000.0,Data_Analyst,Mid_level
90,"Integral Consulting Services, Inc.","Arlington, VA",100000.0,Data_Analyst,Mid_level
91,ESNS,"Herndon, VA",100000.0,Data_Analyst,Mid_level
92,IBM Kenexa,"Washington, DC",100000.0,Data_Analyst,Mid_level
93,IBM,"Washington, DC 20005 (Logan Circle area)",100000.0,Data_Analyst,Mid_level
94,Engility Corporation,"Reston, VA 20191",100000.0,Data_Analyst,Mid_level
95,Modis,"Washington, DC 20036 (Downtown area)",100000.0,Data_Analyst,Mid_level
96,CSRA,"Washington, DC",100000.0,Data_Analyst,Mid_level
97,Gate Staffing,"Washington, DC 20024 (South West area)",100000.0,Data_Analyst,Mid_level
98,Alvarez & Marsal,"Washington, DC 20004 (Downtown area)",100000.0,Data_Analyst,Mid_level
99,"Science System and Applications, Inc.","Greenbelt, MD",100000.0,Data_Analyst,Mid_level
100,TransVoyant,"Alexandria, VA 22303",100000.0,Data_Analyst,Mid_level
101,Asurion,"Sterling, VA",100000.0,Data_Analyst,Mid_level
102,"Orbis Technologies, Inc.","Annapolis, MD",100000.0,Data_Analyst,Mid_level
103,"The Upside Travel Company, LLC","Washington, DC",100000.0,Data_Analyst,Mid_level
104,"FTI Consulting, Inc.","McLean, VA",100000.0,Data_Analyst,Mid_level

## Data_Analyst_DC_100_senior

In [108]:
driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=Washington,+DC&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_DC_100_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_DC_100_senior

,Company_name,Location,Salary,Title,Experience
0,General Dynamics Information Technology,"Springfield, VA",100000.0,Data_Analyst,Senior_level
1,WSSC,"Laurel, MD 20707",100000.0,Data_Analyst,Senior_level
2,Engility Corporation,"Washington, DC",100000.0,Data_Analyst,Senior_level
3,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Senior_level
4,DataNet Systems Corporation,"Washington, DC",100000.0,Data_Analyst,Senior_level
5,Indev,"Washington, DC",100000.0,Data_Analyst,Senior_level
6,Vencore,"McLean, VA",100000.0,Data_Analyst,Senior_level
7,Garud Technology Services Inc.,"Washington, DC",100000.0,Data_Analyst,Senior_level
8,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Senior_level
9,IMTAS,"Washington, DC 20001 (Shaw area)",100000.0,Data_Analyst,Senior_level
10,"Universal Strategy Group, Inc (USGI)","Washington, DC 20535 (Downtown area)",100000.0,Data_Analyst,Senior_level
11,Information Innovators Inc.,"Washington, DC",100000.0,Data_Analyst,Senior_level
12,Hartman Executive Advisors,"Washington, DC",100000.0,Data_Analyst,Senior_level
13,SC3,"Washington, DC",100000.0,Data_Analyst,Senior_level
14,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Senior_level
15,Lockheed Martin,"Washington, DC",100000.0,Data_Analyst,Senior_level
16,ACI Federal,"Baltimore, MD",100000.0,Data_Analyst,Senior_level
17,Systems Support & Integration Inc,"Crystal City, VA",100000.0,Data_Analyst,Senior_level
18,Amtrak,"Washington, DC 20002 (Capitol Hill area)",100000.0,Data_Analyst,Senior_level
19,Booz Allen Hamilton,"Alexandria, VA",100000.0,Data_Analyst,Senior_level
20,Booz Allen Hamilton,"Alexandria, VA",100000.0,Data_Analyst,Senior_level
21,"Goldbelt, Inc.","Washington, DC",100000.0,Data_Analyst,Senior_level
22,phia,"Arlington, VA",100000.0,Data_Analyst,Senior_level
23,Grant Thornton,"Alexandria, VA 22314 (Southwest Quadrant area)",100000.0,Data_Analyst,Senior_level
24,"Laulima Government Solutions, LLC.","Falls Church, VA",100000.0,Data_Analyst,Senior_level
25,Booz Allen Hamilton,"Washington, DC",100000.0,Data_Analyst,Senior_level
26,"Sylver Rain Consulting, llc","Washington, DC 20004 (Downtown area)",100000.0,Data_Analyst,Senior_level
27,The Aerospace Corporation,"Crystal City, VA",100000.0,Data_Analyst,Senior_level
28,Novetta,"Washington, DC",100000.0,Data_Analyst,Senior_level
29,ALQIMI,"Washington, DC",100000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,EXL,"Reston, VA",100000.0,Data_Analyst,Senior_level
76,T. Rowe Price,"Owings Mills, MD",100000.0,Data_Analyst,Senior_level
77,"RTGX, Inc.","Rosslyn, VA",100000.0,Data_Analyst,Senior_level
78,TAC Integrated Solutions,"Arlington, VA",100000.0,Data_Analyst,Senior_level
79,Booz Allen Hamilton,"Falls Church, VA",100000.0,Data_Analyst,Senior_level
80,EXL,"Reston, VA",100000.0,Data_Analyst,Senior_level
81,Booz Allen Hamilton,"Reston, VA",100000.0,Data_Analyst,Senior_level
82,CACI,"Fort Detrick, MD",100000.0,Data_Analyst,Senior_level
83,IntelliWare Systems,"Crystal City, VA",100000.0,Data_Analyst,Senior_level
84,"Kalman & Company, Inc.","Quantico, VA",100000.0,Data_Analyst,Senior_level
85,Leidos,"McLean, VA",100000.0,Data_Analyst,Senior_level
86,Apex Systems Inc,"Rockville, MD",100000.0,Data_Analyst,Senior_level
87,Vencore,"College Park, MD",100000.0,Data_Analyst,Senior_level
88,Exelon,"Baltimore, MD 21223 (West Baltimore area)",100000.0,Data_Analyst,Senior_level
89,"T Solutions, LLC","Washington, DC",100000.0,Data_Analyst,Senior_level
90,IntelliWare Systems,"Washington, DC",100000.0,Data_Analyst,Senior_level
91,Technica Corporation,"Dulles, VA",100000.0,Data_Analyst,Senior_level
92,Leidos,"Washington, DC 20001 (Shaw area)",100000.0,Data_Analyst,Senior_level
93,Yash Solutions LLC,"Washington, DC",100000.0,Data_Analyst,Senior_level
94,SapientNitro,"Arlington, VA",100000.0,Data_Analyst,Senior_level
95,Johns Hopkins University,"Baltimore, MD",100000.0,Data_Analyst,Senior_level
96,ManTech International Corporation,"Washington, DC",100000.0,Data_Analyst,Senior_level
97,iQuasar,"Washington, DC",100000.0,Data_Analyst,Senior_level
98,T. Rowe Price,"Baltimore, MD",100000.0,Data_Analyst,Senior_level
99,SAIC,"Arlington, VA",100000.0,Data_Analyst,Senior_level
100,Raytheon,"Dulles, VA",100000.0,Data_Analyst,Senior_level
101,Assured Consulting Solutions,"Landover, MD",100000.0,Data_Analyst,Senior_level
102,"Integral Consulting Services, Inc.","Rockville, MD",100000.0,Data_Analyst,Senior_level
103,Kearney & Company,"Alexandria, VA 22314",100000.0,Data_Analyst,Senior_level
104,BlackBerry,"Washington, DC",100000.0,Data_Analyst,Senior_level

## New york city

In [109]:
## Data_Analyst_NY_55_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$55,000&l=New+York,+NY&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 55000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_55_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_55_entry

## Data_Analyst_NY_55_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$55,000&l=New+York,+NY&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 55000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_55_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_55_mid

## Data_Analyst_NY_55_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$55,000&l=New+York,+NY&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 55000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_55_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_55_senior

,Company_name,Location,Salary,Title,Experience
0,TD Ameritrade,"Jersey City, NJ",55000.0,Data_Analyst,Senior_level
1,Accenture,"New York, NY 10011",55000.0,Data_Analyst,Senior_level
2,Crystal Run Healthcare,"Middletown, NY 10941",55000.0,Data_Analyst,Senior_level
3,Veterans Sourcing Group,"Brooklyn, NY 11217 (Boerum Hill area)",55000.0,Data_Analyst,Senior_level
4,Grubhub,"New York, NY",55000.0,Data_Analyst,Senior_level
5,MassMutual Financial Group,"New York, NY",55000.0,Data_Analyst,Senior_level
6,American Express,"New York, NY",55000.0,Data_Analyst,Senior_level
7,MAYORS OFFICE OF CONTRACT SVCS,"Manhattan, NY",55000.0,Data_Analyst,Senior_level
8,FAIR Health,"New York, NY 10017 (Midtown area)",55000.0,Data_Analyst,Senior_level
9,Dow Jones,"New York, NY 10176 (Murray Hill area)",55000.0,Data_Analyst,Senior_level
10,Razorfish,"New York, NY",55000.0,Data_Analyst,Senior_level
11,Veterans Sourcing Group,"Berkeley Heights, NJ 07922",55000.0,Data_Analyst,Senior_level
12,ArborSys Group,"Bridgewater, NJ 08807",55000.0,Data_Analyst,Senior_level
13,Johnson & Johnson,"New Brunswick, NJ",55000.0,Data_Analyst,Senior_level
14,Major League Baseball Advanced Media,"New York, NY",55000.0,Data_Analyst,Senior_level
15,Sapient Global Markets,"New York, NY",55000.0,Data_Analyst,Senior_level
16,Undertone,"New York, NY 10173 (Midtown area)",55000.0,Data_Analyst,Senior_level
17,"Gartner, Inc.","Stamford, CT 06902 (Downtown area)",55000.0,Data_Analyst,Senior_level
18,IAC Applications,"Yonkers, NY",55000.0,Data_Analyst,Senior_level
19,NYU Langone Medical Center,"New York, NY",55000.0,Data_Analyst,Senior_level
20,TIAA,"New York, NY 10002 (Lower East Side area)",55000.0,Data_Analyst,Senior_level
21,Moody's Shared Services,"New York, NY",55000.0,Data_Analyst,Senior_level
22,Attention,"New York, NY",55000.0,Data_Analyst,Senior_level
23,"Brooks Brothers Group, Inc","New York, NY",55000.0,Data_Analyst,Senior_level
24,Mount Sinai Health System,"New York, NY 10029 (Yorkville area)",55000.0,Data_Analyst,Senior_level
25,Meetup,"New York, NY 10012 (Little Italy area)",55000.0,Data_Analyst,Senior_level
26,Univision communications inc,"New York, NY",55000.0,Data_Analyst,Senior_level
27,"Kani Soutions, Inc","New York, NY 10019 (Midtown area)",55000.0,Data_Analyst,Senior_level
28,CDM New York,"New York, NY",55000.0,Data_Analyst,Senior_level
29,TD Ameritrade,"Jersey City, NJ",55000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Spotify,"New York, NY 10011 (Chelsea area)",55000.0,Data_Analyst,Senior_level
76,INTL FCStone,"New York, NY",55000.0,Data_Analyst,Senior_level
77,"Intercontinental Exchange, Inc.","New York, NY 10022 (Midtown area)",55000.0,Data_Analyst,Senior_level
78,EZOPS,"New Brunswick, NJ",55000.0,Data_Analyst,Senior_level
79,Rockwell Collins,"New York, NY",55000.0,Data_Analyst,Senior_level
80,Altice USA Cable Operations,"Bethpage, NY",55000.0,Data_Analyst,Senior_level
81,NICE,"Hoboken, NJ",55000.0,Data_Analyst,Senior_level
82,RAYMOND JAMES FINANCIAL,"New York, NY",55000.0,Data_Analyst,Senior_level
83,Dow Jones,"Princeton, NJ 08542",55000.0,Data_Analyst,Senior_level
84,CAPCO,"New York, NY 10271 (Financial District area)",55000.0,Data_Analyst,Senior_level
85,Rockstar New York,"New York, NY",55000.0,Data_Analyst,Senior_level
86,Veterans Sourcing Group,"New Brunswick, NJ 08903",55000.0,Data_Analyst,Senior_level
87,Healthfirst,"New York, NY",55000.0,Data_Analyst,Senior_level
88,AIG,"New York, NY",55000.0,Data_Analyst,Senior_level
89,Aetna,"New York, NY 10016 (Gramercy area)",55000.0,Data_Analyst,Senior_level
90,Oliver James Associates,"New York, NY",55000.0,Data_Analyst,Senior_level
91,Analytic Recruiting,"New York, NY 10017 (Midtown area)",55000.0,Data_Analyst,Senior_level
92,American Express,"New York, NY",55000.0,Data_Analyst,Senior_level
93,Perella Weinberg Partners,"New York, NY 10153 (Midtown area)",55000.0,Data_Analyst,Senior_level
94,Charter Communications,"Stamford, CT",55000.0,Data_Analyst,Senior_level
95,eSystems Inc.,"Princeton, NJ 08540",55000.0,Data_Analyst,Senior_level
96,Veterans Sourcing Group,"Lawrenceville, NJ",55000.0,Data_Analyst,Senior_level
97,Selby Jennings,"New York, NY 10167 (Midtown area)",55000.0,Data_Analyst,Senior_level
98,Mount Sinai Health System,"New York, NY 10019 (Midtown area)",55000.0,Data_Analyst,Senior_level
99,MAYORS OFFICE OF CONTRACT SVCS,"Manhattan, NY",55000.0,Data_Analyst,Senior_level
100,McGraw-Hill Education,"New York, NY",55000.0,Data_Analyst,Senior_level
101,"Hill & Knowlton, Inc.","New York, NY",55000.0,Data_Analyst,Senior_level
102,News Corp,"New York, NY 10036",55000.0,Data_Analyst,Senior_level
103,Prudential,"Newark, NJ 07101",55000.0,Data_Analyst,Senior_level
104,Prudential,"Newark, NJ 07102",55000.0,Data_Analyst,Senior_level

In [110]:
##Data_Analyst_NY_70_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=New+York,+NY&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_70_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_70_entry

## Data_Analyst_NY_70_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=New+York,+NY&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_70_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_70_mid

## Data_Analyst_NY_70_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$70,000&l=New+York,+NY&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 70000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_70_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_70_senior

,Company_name,Location,Salary,Title,Experience
0,TD Ameritrade,"Jersey City, NJ",70000.0,Data_Analyst,Senior_level
1,Prudential,"Newark, NJ 07101",70000.0,Data_Analyst,Senior_level
2,TD Bank,"Mount Laurel, NJ",70000.0,Data_Analyst,Senior_level
3,Veterans Sourcing Group,"Brooklyn, NY 11217 (Boerum Hill area)",70000.0,Data_Analyst,Senior_level
4,Grubhub,"New York, NY",70000.0,Data_Analyst,Senior_level
5,MassMutual Financial Group,"New York, NY",70000.0,Data_Analyst,Senior_level
6,American Express,"New York, NY",70000.0,Data_Analyst,Senior_level
7,MAYORS OFFICE OF CONTRACT SVCS,"Manhattan, NY",70000.0,Data_Analyst,Senior_level
8,FAIR Health,"New York, NY 10017 (Midtown area)",70000.0,Data_Analyst,Senior_level
9,Razorfish,"New York, NY",70000.0,Data_Analyst,Senior_level
10,ArborSys Group,"Bridgewater, NJ 08807",70000.0,Data_Analyst,Senior_level
11,Major League Baseball Advanced Media,"New York, NY",70000.0,Data_Analyst,Senior_level
12,Sapient Global Markets,"New York, NY",70000.0,Data_Analyst,Senior_level
13,Undertone,"New York, NY 10173 (Midtown area)",70000.0,Data_Analyst,Senior_level
14,"Gartner, Inc.","Stamford, CT 06902 (Downtown area)",70000.0,Data_Analyst,Senior_level
15,IAC Applications,"Yonkers, NY",70000.0,Data_Analyst,Senior_level
16,NYU Langone Medical Center,"New York, NY",70000.0,Data_Analyst,Senior_level
17,TIAA,"New York, NY 10002 (Lower East Side area)",70000.0,Data_Analyst,Senior_level
18,Moody's Shared Services,"New York, NY",70000.0,Data_Analyst,Senior_level
19,Veterans Sourcing Group,"Berkeley Heights, NJ 07922",70000.0,Data_Analyst,Senior_level
20,"Brooks Brothers Group, Inc","New York, NY",70000.0,Data_Analyst,Senior_level
21,Mount Sinai Health System,"New York, NY 10029 (Yorkville area)",70000.0,Data_Analyst,Senior_level
22,Meetup,"New York, NY 10012 (Little Italy area)",70000.0,Data_Analyst,Senior_level
23,Univision communications inc,"New York, NY",70000.0,Data_Analyst,Senior_level
24,"Kani Soutions, Inc","New York, NY 10019 (Midtown area)",70000.0,Data_Analyst,Senior_level
25,CDM New York,"New York, NY",70000.0,Data_Analyst,Senior_level
26,TD Ameritrade,"Jersey City, NJ",70000.0,Data_Analyst,Senior_level
27,Capital One,"New York, NY",70000.0,Data_Analyst,Senior_level
28,American Express,"New York, NY",70000.0,Data_Analyst,Senior_level
29,SQA Solution,"New York, NY",70000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Dow Jones,"Princeton, NJ 08542",70000.0,Data_Analyst,Senior_level
76,CAPCO,"New York, NY 10271 (Financial District area)",70000.0,Data_Analyst,Senior_level
77,Rockstar New York,"New York, NY",70000.0,Data_Analyst,Senior_level
78,Veterans Sourcing Group,"New Brunswick, NJ 08903",70000.0,Data_Analyst,Senior_level
79,AIG,"New York, NY",70000.0,Data_Analyst,Senior_level
80,Aetna,"New York, NY 10016 (Gramercy area)",70000.0,Data_Analyst,Senior_level
81,Oliver James Associates,"New York, NY",70000.0,Data_Analyst,Senior_level
82,Analytic Recruiting,"New York, NY 10017 (Midtown area)",70000.0,Data_Analyst,Senior_level
83,Perella Weinberg Partners,"New York, NY 10153 (Midtown area)",70000.0,Data_Analyst,Senior_level
84,eSystems Inc.,"Princeton, NJ 08540",70000.0,Data_Analyst,Senior_level
85,Veterans Sourcing Group,"Lawrenceville, NJ",70000.0,Data_Analyst,Senior_level
86,Selby Jennings,"New York, NY 10167 (Midtown area)",70000.0,Data_Analyst,Senior_level
87,Mount Sinai Health System,"New York, NY 10019 (Midtown area)",70000.0,Data_Analyst,Senior_level
88,MAYORS OFFICE OF CONTRACT SVCS,"Manhattan, NY",70000.0,Data_Analyst,Senior_level
89,McGraw-Hill Education,"New York, NY",70000.0,Data_Analyst,Senior_level
90,"Hill & Knowlton, Inc.","New York, NY",70000.0,Data_Analyst,Senior_level
91,News Corp,"New York, NY 10036",70000.0,Data_Analyst,Senior_level
92,Johnson & Johnson Services Inc.,"New Brunswick, NJ",70000.0,Data_Analyst,Senior_level
93,Freddie Mac,"New York, NY 10168 (Murray Hill area)",70000.0,Data_Analyst,Senior_level
94,CONSUMER AFFAIRS,"Manhattan, NY",70000.0,Data_Analyst,Senior_level
95,"J.Crew Group, Inc.","New York, NY 10003 (Greenwich Village area)",70000.0,Data_Analyst,Senior_level
96,"Broadridge Financial Solutions, Inc.","Edgewood, NY 11717",70000.0,Data_Analyst,Senior_level
97,Brooklyn Data Science,"New York, NY",70000.0,Data_Analyst,Senior_level
98,ULTRA Mobile,"Long Island, NY",70000.0,Data_Analyst,Senior_level
99,NetBase Solutions,"New York, NY",70000.0,Data_Analyst,Senior_level
100,Two95 International Inc.,"New York, NY",70000.0,Data_Analyst,Senior_level
101,Informa Business Intelligence,"New York, NY",70000.0,Data_Analyst,Senior_level
102,Express Scripts,"Franklin Lakes, NJ 07417",70000.0,Data_Analyst,Senior_level
103,Accenture,"New York, NY 10011",70000.0,Data_Analyst,Senior_level
104,Prudential,"Newark, NJ 07102",70000.0,Data_Analyst,Senior_level

In [111]:
##Data_Analyst_NY_85_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=New+York,+NY&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_85_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_85_entry

##Data_Analyst_NY_85_mid


driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=New+York,+NY&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_85_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_85_mid

##Data_Analyst_NY_85_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=New+York,+NY&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_85_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_85_senior

,Company_name,Location,Salary,Title,Experience
0,Crystal Run Healthcare,"Middletown, NY 10941",85000.0,Data_Analyst,Senior_level
1,Accenture,"New York, NY 10011",85000.0,Data_Analyst,Senior_level
2,Weill Cornell Medical College,"New York, NY",85000.0,Data_Analyst,Senior_level
3,Grubhub,"New York, NY",85000.0,Data_Analyst,Senior_level
4,American Express,"New York, NY",85000.0,Data_Analyst,Senior_level
5,Veterans Sourcing Group,"Berkeley Heights, NJ 07922",85000.0,Data_Analyst,Senior_level
6,MassMutual Financial Group,"New York, NY",85000.0,Data_Analyst,Senior_level
7,FAIR Health,"New York, NY 10017 (Midtown area)",85000.0,Data_Analyst,Senior_level
8,Sapient Global Markets,"New York, NY",85000.0,Data_Analyst,Senior_level
9,Undertone,"New York, NY 10173 (Midtown area)",85000.0,Data_Analyst,Senior_level
10,Major League Baseball Advanced Media,"New York, NY",85000.0,Data_Analyst,Senior_level
11,TIAA,"New York, NY 10002 (Lower East Side area)",85000.0,Data_Analyst,Senior_level
12,Moody's Shared Services,"New York, NY",85000.0,Data_Analyst,Senior_level
13,Meetup,"New York, NY 10012 (Little Italy area)",85000.0,Data_Analyst,Senior_level
14,Capital One,"New York, NY",85000.0,Data_Analyst,Senior_level
15,"Kani Soutions, Inc","New York, NY 10019 (Midtown area)",85000.0,Data_Analyst,Senior_level
16,American Express,"New York, NY",85000.0,Data_Analyst,Senior_level
17,Knowledgent Group Inc.,"New York, NY",85000.0,Data_Analyst,Senior_level
18,Arup,"New York, NY",85000.0,Data_Analyst,Senior_level
19,Fareportal Inc.,"New York, NY 10020 (Midtown area)",85000.0,Data_Analyst,Senior_level
20,Yodle,"New York, NY 10001 (Chelsea area)",85000.0,Data_Analyst,Senior_level
21,SQA Solution,"New York, NY",85000.0,Data_Analyst,Senior_level
22,Church Pension Group,"New York, NY",85000.0,Data_Analyst,Senior_level
23,Paperless Post,"New York, NY",85000.0,Data_Analyst,Senior_level
24,JPMorgan Chase,"New York, NY",85000.0,Data_Analyst,Senior_level
25,WeWork,"New York, NY 10005 (Financial District area)",85000.0,Data_Analyst,Senior_level
26,OrthoNet,"White Plains, NY 10605",85000.0,Data_Analyst,Senior_level
27,HSBC,"New York, NY",85000.0,Data_Analyst,Senior_level
28,Huxley Banking & Financial Services,"New York, NY",85000.0,Data_Analyst,Senior_level
29,Spreemo,"New York, NY",85000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Citi,"New York, NY",85000.0,Data_Analyst,Senior_level
76,McGraw-Hill Education,"New York, NY",85000.0,Data_Analyst,Senior_level
77,SiriusXM,"Township of Lawrence, NJ 08648",85000.0,Data_Analyst,Senior_level
78,IRI,"Stamford, CT",85000.0,Data_Analyst,Senior_level
79,BNY Mellon,"New York, NY",85000.0,Data_Analyst,Senior_level
80,Chubb,"Whitehouse Station, NJ",85000.0,Data_Analyst,Senior_level
81,"Broadridge Financial Solutions, Inc.","Edgewood, NY 11717",85000.0,Data_Analyst,Senior_level
82,FIS,"New York, NY 10034 (Inwood area)",85000.0,Data_Analyst,Senior_level
83,Starcom,"New York, NY",85000.0,Data_Analyst,Senior_level
84,CONSUMER AFFAIRS,"Manhattan, NY",85000.0,Data_Analyst,Senior_level
85,Veterans Sourcing Group,"New Brunswick, NJ 08903",85000.0,Data_Analyst,Senior_level
86,Li & Fung,"New York, NY 10018 (Clinton area)",85000.0,Data_Analyst,Senior_level
87,Mitchell Martin,"Long Island City, NY 11101",85000.0,Data_Analyst,Senior_level
88,Averity,"New York, NY",85000.0,Data_Analyst,Senior_level
89,Freddie Mac,"New York, NY 10168 (Murray Hill area)",85000.0,Data_Analyst,Senior_level
90,Informa Business Intelligence,"New York, NY",85000.0,Data_Analyst,Senior_level
91,Global Data Management Inc,"New York, NY 10018 (Clinton area)",85000.0,Data_Analyst,Senior_level
92,AIG,"New York, NY",85000.0,Data_Analyst,Senior_level
93,Johnson & Johnson Services Inc.,"New Brunswick, NJ",85000.0,Data_Analyst,Senior_level
94,"Horizon Media, Inc.","New York, NY",85000.0,Data_Analyst,Senior_level
95,Wolters Kluwer,"New York, NY",85000.0,Data_Analyst,Senior_level
96,SiriusXM,"New York, NY 10001 (Chelsea area)",85000.0,Data_Analyst,Senior_level
97,"J.Crew Group, Inc.","New York, NY 10003 (Greenwich Village area)",85000.0,Data_Analyst,Senior_level
98,Zealogics,"Tarrytown, NY",85000.0,Data_Analyst,Senior_level
99,Veterans Sourcing Group,"Lawrenceville, NJ",85000.0,Data_Analyst,Senior_level
100,Avesta Computer Services,"Morristown, NJ",85000.0,Data_Analyst,Senior_level
101,Pivotal Software,"New York, NY 10017 (Midtown area)",85000.0,Data_Analyst,Senior_level
102,Enigma,"New York, NY",85000.0,Data_Analyst,Senior_level
103,TD Bank,"Mount Laurel, NJ",85000.0,Data_Analyst,Senior_level
104,Prudential,"Newark, NJ 07102",85000.0,Data_Analyst,Senior_level

In [112]:
##Data_Analyst_NY_95_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$95,000&l=New+York,+NY&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 95000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_95_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_95_entry

##Data_Analyst_NY_125_mid


driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$95,000&l=New+York,+NY&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 95000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_95_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_95_mid

##Data_Analyst_NY_95_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$95,000&l=New+York,+NY&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 95000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_95_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_95_senior

,Company_name,Location,Salary,Title,Experience
0,Prudential,"Newark, NJ 07102",95000.0,Data_Analyst,Senior_level
1,Crystal Run Healthcare,"Middletown, NY 10941",95000.0,Data_Analyst,Senior_level
2,Citi,"Long Island City, NY",95000.0,Data_Analyst,Senior_level
3,MassMutual Financial Group,"New York, NY",95000.0,Data_Analyst,Senior_level
4,FAIR Health,"New York, NY 10017 (Midtown area)",95000.0,Data_Analyst,Senior_level
5,Veterans Sourcing Group,"Berkeley Heights, NJ 07922",95000.0,Data_Analyst,Senior_level
6,Grubhub,"New York, NY",95000.0,Data_Analyst,Senior_level
7,Major League Baseball Advanced Media,"New York, NY",95000.0,Data_Analyst,Senior_level
8,Sapient Global Markets,"New York, NY",95000.0,Data_Analyst,Senior_level
9,WeWork,"New York, NY 10005 (Financial District area)",95000.0,Data_Analyst,Senior_level
10,TIAA,"New York, NY 10002 (Lower East Side area)",95000.0,Data_Analyst,Senior_level
11,Meetup,"New York, NY 10012 (Little Italy area)",95000.0,Data_Analyst,Senior_level
12,Capital One,"New York, NY",95000.0,Data_Analyst,Senior_level
13,SQA Solution,"New York, NY",95000.0,Data_Analyst,Senior_level
14,Arup,"New York, NY",95000.0,Data_Analyst,Senior_level
15,Refinery29,"New York, NY 10013 (Tribeca area)",95000.0,Data_Analyst,Senior_level
16,JPMorgan Chase,"New York, NY",95000.0,Data_Analyst,Senior_level
17,Church Pension Group,"New York, NY",95000.0,Data_Analyst,Senior_level
18,Paperless Post,"New York, NY",95000.0,Data_Analyst,Senior_level
19,Fareportal Inc.,"New York, NY 10020 (Midtown area)",95000.0,Data_Analyst,Senior_level
20,WeWork,"New York, NY 10005 (Financial District area)",95000.0,Data_Analyst,Senior_level
21,Momentum,"New York, NY 10013 (Tribeca area)",95000.0,Data_Analyst,Senior_level
22,SiriusXM,"New York, NY 10001 (Chelsea area)",95000.0,Data_Analyst,Senior_level
23,SoHo Dragon,"New York, NY 10004 (Financial District area)",95000.0,Data_Analyst,Senior_level
24,Spreemo,"New York, NY",95000.0,Data_Analyst,Senior_level
25,QuintilesIMS,"New York, NY",95000.0,Data_Analyst,Senior_level
26,HARITA INFOTECH,"New York, NY",95000.0,Data_Analyst,Senior_level
27,HSBC,"New York, NY",95000.0,Data_Analyst,Senior_level
28,ZS Associates,"New York, NY 10017 (Midtown area)",95000.0,Data_Analyst,Senior_level
29,Huxley Banking & Financial Services,"New York, NY",95000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Pivotal Software,"New York, NY 10017 (Midtown area)",95000.0,Data_Analyst,Senior_level
76,CoStar Group,"New York, NY",95000.0,Data_Analyst,Senior_level
77,Averity,"New York, NY",95000.0,Data_Analyst,Senior_level
78,L'Oreal USA,"New York, NY",95000.0,Data_Analyst,Senior_level
79,Veterans Sourcing Group,"New York, NY 10004 (Financial District area)",95000.0,Data_Analyst,Senior_level
80,Outbrain Inc.,"New York, NY",95000.0,Data_Analyst,Senior_level
81,BNY Mellon,"New York, NY",95000.0,Data_Analyst,Senior_level
82,BNP Paribas,"New York, NY",95000.0,Data_Analyst,Senior_level
83,Yash Solutions LLC,"Brooklyn, NY",95000.0,Data_Analyst,Senior_level
84,Enigma,"New York, NY",95000.0,Data_Analyst,Senior_level
85,BNY Mellon,"New York, NY",95000.0,Data_Analyst,Senior_level
86,EXL,"Jersey City, NJ",95000.0,Data_Analyst,Senior_level
87,Boehringer Ingelheim,"Ridgefield, CT",95000.0,Data_Analyst,Senior_level
88,Priceline.com,"Norwalk, CT 06854",95000.0,Data_Analyst,Senior_level
89,CBS Corporate,"New York, NY 10176 (Murray Hill area)",95000.0,Data_Analyst,Senior_level
90,New York Life Insurance Co,"Jersey City, NJ 07302 (Downtown area)",95000.0,Data_Analyst,Senior_level
91,Avesta Computer Services,"Morristown, NJ",95000.0,Data_Analyst,Senior_level
92,Endurance,"New York, NY 10018 (Clinton area)",95000.0,Data_Analyst,Senior_level
93,Salesforce,"New York, NY 10017 (Midtown area)",95000.0,Data_Analyst,Senior_level
94,Sumitomo Mitsui Banking Corporation.,"New York, NY 10172 (Gramercy area)",95000.0,Data_Analyst,Senior_level
95,Fleishman-Hillard,"New York, NY",95000.0,Data_Analyst,Senior_level
96,Citi,"Long Island City, NY",95000.0,Data_Analyst,Senior_level
97,Bloomberg,"New York, NY",95000.0,Data_Analyst,Senior_level
98,Godiva Chocolatier Inc.,"New York, NY",95000.0,Data_Analyst,Senior_level
99,Ross Stores,"New York, NY",95000.0,Data_Analyst,Senior_level
100,Blue Apron,"New York, NY 10013 (Tribeca area)",95000.0,Data_Analyst,Senior_level
101,Allergan,"Jersey City, NJ",95000.0,Data_Analyst,Senior_level
102,Tumblr,"New York, NY",95000.0,Data_Analyst,Senior_level
103,TD Bank,"Mount Laurel, NJ",95000.0,Data_Analyst,Senior_level
104,Accenture,"New York, NY 10011",95000.0,Data_Analyst,Senior_level

In [113]:
## Data_Analyst_NY_115_entry


driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=New+York,+NY&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_115_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_115_entry

##Data_Analyst_NY_115_mid


driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=New+York,+NY&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_115_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_115_mid

##Data_Analyst_NY_115_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=New+York,+NY&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_NY_115_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_NY_115_senior

,Company_name,Location,Salary,Title,Experience
0,Prudential,"Newark, NJ 07102",115000.0,Data_Analyst,Senior_level
1,Citi,"Long Island City, NY",115000.0,Data_Analyst,Senior_level
2,Princeton Consulting,"New York, NY 10018",115000.0,Data_Analyst,Senior_level
3,Grubhub,"New York, NY",115000.0,Data_Analyst,Senior_level
4,Sapient Global Markets,"New York, NY",115000.0,Data_Analyst,Senior_level
5,Major League Baseball Advanced Media,"New York, NY",115000.0,Data_Analyst,Senior_level
6,Capital One,"New York, NY",115000.0,Data_Analyst,Senior_level
7,Paperless Post,"New York, NY",115000.0,Data_Analyst,Senior_level
8,JPMorgan Chase,"New York, NY",115000.0,Data_Analyst,Senior_level
9,WeWork,"New York, NY 10005 (Financial District area)",115000.0,Data_Analyst,Senior_level
10,HSBC,"New York, NY",115000.0,Data_Analyst,Senior_level
11,Huxley Banking & Financial Services,"New York, NY",115000.0,Data_Analyst,Senior_level
12,Spreemo,"New York, NY",115000.0,Data_Analyst,Senior_level
13,Momentum,"New York, NY 10013 (Tribeca area)",115000.0,Data_Analyst,Senior_level
14,ZS Associates,"New York, NY 10017 (Midtown area)",115000.0,Data_Analyst,Senior_level
15,GroupM,"New York, NY",115000.0,Data_Analyst,Senior_level
16,Spotify,"New York, NY 10011 (Chelsea area)",115000.0,Data_Analyst,Senior_level
17,Absolutdata,"New York, NY",115000.0,Data_Analyst,Senior_level
18,1stdibs.com,"New York, NY",115000.0,Data_Analyst,Senior_level
19,Analytic Recruiting,"New York, NY 10017 (Midtown area)",115000.0,Data_Analyst,Senior_level
20,NICE,"Hoboken, NJ",115000.0,Data_Analyst,Senior_level
21,AIG,"New York, NY",115000.0,Data_Analyst,Senior_level
22,RAYMOND JAMES FINANCIAL,"New York, NY",115000.0,Data_Analyst,Senior_level
23,"Hill & Knowlton, Inc.","New York, NY",115000.0,Data_Analyst,Senior_level
24,Rockstar New York,"New York, NY",115000.0,Data_Analyst,Senior_level
25,Aetna,"New York, NY 10016 (Gramercy area)",115000.0,Data_Analyst,Senior_level
26,Mercury Media,"New York, NY 10005 (Financial District area)",115000.0,Data_Analyst,Senior_level
27,Brooklyn Data Science,"New York, NY",115000.0,Data_Analyst,Senior_level
28,AT&T,"New York, NY",115000.0,Data_Analyst,Senior_level
29,Johnson & Johnson Services Inc.,"New Brunswick, NJ",115000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,"NSD International, Inc.","New York, NY 10020 (Midtown area)",115000.0,Data_Analyst,Senior_level
76,Harnham,"New York, NY",115000.0,Data_Analyst,Senior_level
77,Société Générale,"New York, NY",115000.0,Data_Analyst,Senior_level
78,Analysts International,"Manhattan, NY",115000.0,Data_Analyst,Senior_level
79,KCS,"New York, NY",115000.0,Data_Analyst,Senior_level
80,Allergan,"Parsippany, NJ",115000.0,Data_Analyst,Senior_level
81,Selby Jennings,"New York, NY 10167 (Midtown area)",115000.0,Data_Analyst,Senior_level
82,2U,"New York, NY",115000.0,Data_Analyst,Senior_level
83,JPMorgan Chase,"Jersey City, NJ",115000.0,Data_Analyst,Senior_level
84,Eurasia Group,"New York, NY 10017 (Midtown area)",115000.0,Data_Analyst,Senior_level
85,NICE Systems,"Hoboken, NJ",115000.0,Data_Analyst,Senior_level
86,JPMorgan Chase,"Jersey City, NJ",115000.0,Data_Analyst,Senior_level
87,Harnham,"New York, NY",115000.0,Data_Analyst,Senior_level
88,BAE Systems Applied Intelligence,"New York, NY",115000.0,Data_Analyst,Senior_level
89,Wunderman,"New York, NY 10017 (Midtown area)",115000.0,Data_Analyst,Senior_level
90,Capital One,"New York, NY",115000.0,Data_Analyst,Senior_level
91,Veterans Sourcing Group,"New York, NY 10179 (Midtown area)",115000.0,Data_Analyst,Senior_level
92,Selby Jennings,"New York, NY 10167 (Midtown area)",115000.0,Data_Analyst,Senior_level
93,CIT Group,"New York, NY 10036",115000.0,Data_Analyst,Senior_level
94,New York Life Insurance Co,"Jersey City, NJ 07302 (Downtown area)",115000.0,Data_Analyst,Senior_level
95,Linium,"New York, NY",115000.0,Data_Analyst,Senior_level
96,Employment Staffing,"New York, NY",115000.0,Data_Analyst,Senior_level
97,OFFICE OF THE COMPTROLLER,"New York, NY 10007 (Financial District area)",115000.0,Data_Analyst,Senior_level
98,Ipreo,"New York, NY",115000.0,Data_Analyst,Senior_level
99,TravelCLICK,"New York, NY 10018 (Clinton area)",115000.0,Data_Analyst,Senior_level
100,Dynamics Associates,"New York, NY",115000.0,Data_Analyst,Senior_level
101,Priceline.com,"Norwalk, CT 06854",115000.0,Data_Analyst,Senior_level
102,Smith Arnold Partners,"New York, NY",115000.0,Data_Analyst,Senior_level
103,"NSD International, Inc.","New York, NY 10020",115000.0,Data_Analyst,Senior_level
104,TD Bank,"Mount Laurel, NJ",115000.0,Data_Analyst,Senior_level

## San francisco

In [114]:
## Data_Analyst_SF_60_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000&l=San+Francisco,+CA&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_60_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_60_entry

## Data_Analyst_SF_60_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000&l=San+Francisco,+CA&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_60_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_60_mid

## Data_Analyst_SF_60_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$60,000&l=San+Francisco,+CA&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 60000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_60_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_60_senior

,Company_name,Location,Salary,Title,Experience
0,Freedom Financial Network,"San Mateo, CA 94402",60000.0,Data_Analyst,Senior_level
1,Stanford Health Care,"Palo Alto, CA 94305",60000.0,Data_Analyst,Senior_level
2,iRhythm,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
3,Genentech,"South San Francisco, CA",60000.0,Data_Analyst,Senior_level
4,iSoft Solutions,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
5,Athleta,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
6,"Cisco Systems, Inc.","San Jose, CA",60000.0,Data_Analyst,Senior_level
7,Intuit,"Mountain View, CA 94039",60000.0,Data_Analyst,Senior_level
8,Nuna,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
9,Google,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
10,Manage,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
11,Hired,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
12,Capital One,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
13,GE Careers,"San Ramon, CA 94583",60000.0,Data_Analyst,Senior_level
14,RichRelevance,"San Francisco, CA 94111 (Financial District area)",60000.0,Data_Analyst,Senior_level
15,Capital One,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
16,Genentech,"South San Francisco, CA",60000.0,Data_Analyst,Senior_level
17,University of California Office of the...,"Oakland, CA 94607 (Acorn-Acorn Industrial area)",60000.0,Data_Analyst,Senior_level
18,Intel,"Santa Clara, CA 95052",60000.0,Data_Analyst,Senior_level
19,City & County of San Francisco,"San Francisco, CA 94124 (Bayview area)",60000.0,Data_Analyst,Senior_level
20,Maxton & Company,"San Francisco, CA 94110 (Mission area)",60000.0,Data_Analyst,Senior_level
21,Medallia Inc,"Palo Alto, CA 94306 (Barron Park area)",60000.0,Data_Analyst,Senior_level
22,MachineZone,"Palo Alto, CA",60000.0,Data_Analyst,Senior_level
23,CA Technologies,"Santa Clara, CA",60000.0,Data_Analyst,Senior_level
24,Roche,"Santa Clara, CA",60000.0,Data_Analyst,Senior_level
25,Mentor Graphics,"Fremont, CA 94538 (Irvington area)",60000.0,Data_Analyst,Senior_level
26,Arthur Lawrence,"Sunnyvale, CA",60000.0,Data_Analyst,Senior_level
27,"Udacity, Inc.","San Francisco, CA",60000.0,Data_Analyst,Senior_level
28,Poshmark,"Redwood City, CA",60000.0,Data_Analyst,Senior_level
29,Sutter Health,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,"Cisco Systems, Inc.","Santa Clara, CA",60000.0,Data_Analyst,Senior_level
76,ab star group,"San Jose, CA",60000.0,Data_Analyst,Senior_level
77,Wells Fargo,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
78,Symantec,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
79,Dolby,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
80,Thomson Reuters,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
81,Blue Shield of California,"San Francisco, CA 94105 (Financial District area)",60000.0,Data_Analyst,Senior_level
82,GE Careers,"San Ramon, CA 94583",60000.0,Data_Analyst,Senior_level
83,eTeam Inc.,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
84,Google,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
85,addastaff,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
86,Silicon Valley Bank,"Santa Clara, CA 95054",60000.0,Data_Analyst,Senior_level
87,MINDTREE,"San Francisco, CA",60000.0,Data_Analyst,Senior_level
88,Acuitus,"Palo Alto, CA",60000.0,Data_Analyst,Senior_level
89,Visa,"Foster City, CA",60000.0,Data_Analyst,Senior_level
90,CSI Consulting,"San Jose, CA",60000.0,Data_Analyst,Senior_level
91,Symantec,"Mountain View, CA",60000.0,Data_Analyst,Senior_level
92,RideCell,"San Francisco, CA 94103 (South Of Market area)",60000.0,Data_Analyst,Senior_level
93,Dell,"Santa Clara, CA",60000.0,Data_Analyst,Senior_level
94,Plex,"Pleasanton, CA",60000.0,Data_Analyst,Senior_level
95,Quantifind,"Menlo Park, CA",60000.0,Data_Analyst,Senior_level
96,Sony Interactive Entertainment PlayStation,"San Mateo, CA",60000.0,Data_Analyst,Senior_level
97,Paypal,"San Jose, CA",60000.0,Data_Analyst,Senior_level
98,Sony Interactive Entertainment PlayStation,"San Mateo, CA",60000.0,Data_Analyst,Senior_level
99,"InfoVision, Inc.","San Jose, CA",60000.0,Data_Analyst,Senior_level
100,Uber,"Palo Alto, CA 94304",60000.0,Data_Analyst,Senior_level
101,TEKsystems,"San Francisco, CA 94103 (South Of Market area)",60000.0,Data_Analyst,Senior_level
102,MachineZone,"Palo Alto, CA",60000.0,Data_Analyst,Senior_level
103,Genentech,"South San Francisco, CA",60000.0,Data_Analyst,Senior_level
104,Uber,"San Francisco, CA 94105",60000.0,Data_Analyst,Senior_level

In [115]:
## Data_Analyst_sf_75_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=San+Francisco,+CA&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_75_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_75_entry

## Data_Analyst_SF_75_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=San+Francisco,+CA&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_75_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_75_mid

## Data_Analyst_SF_75_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$75,000&l=San+Francisco,+CA&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 75000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_75_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_75_senior

,Company_name,Location,Salary,Title,Experience
0,Freedom Financial Network,"San Mateo, CA 94402",75000.0,Data_Analyst,Senior_level
1,Stanford Health Care,"Palo Alto, CA 94305",75000.0,Data_Analyst,Senior_level
2,Genentech,"South San Francisco, CA",75000.0,Data_Analyst,Senior_level
3,iSoft Solutions,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
4,Genentech,"South San Francisco, CA",75000.0,Data_Analyst,Senior_level
5,"Cisco Systems, Inc.","San Jose, CA",75000.0,Data_Analyst,Senior_level
6,Athleta,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
7,Intuit,"Mountain View, CA 94039",75000.0,Data_Analyst,Senior_level
8,Nuna,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
9,Google,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
10,Manage,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
11,Capital One,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
12,RichRelevance,"San Francisco, CA 94111 (Financial District area)",75000.0,Data_Analyst,Senior_level
13,Intel,"Santa Clara, CA 95052",75000.0,Data_Analyst,Senior_level
14,Capital One,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
15,Hired,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
16,GE Careers,"San Ramon, CA 94583",75000.0,Data_Analyst,Senior_level
17,Genentech,"South San Francisco, CA",75000.0,Data_Analyst,Senior_level
18,University of California Office of the...,"Oakland, CA 94607 (Acorn-Acorn Industrial area)",75000.0,Data_Analyst,Senior_level
19,CA Technologies,"Santa Clara, CA",75000.0,Data_Analyst,Senior_level
20,Google,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
21,MachineZone,"Palo Alto, CA",75000.0,Data_Analyst,Senior_level
22,Arthur Lawrence,"Sunnyvale, CA",75000.0,Data_Analyst,Senior_level
23,City & County of San Francisco,"San Francisco, CA 94124 (Bayview area)",75000.0,Data_Analyst,Senior_level
24,Maxton & Company,"San Francisco, CA 94110 (Mission area)",75000.0,Data_Analyst,Senior_level
25,Medallia Inc,"Palo Alto, CA 94306 (Barron Park area)",75000.0,Data_Analyst,Senior_level
26,Poshmark,"Redwood City, CA",75000.0,Data_Analyst,Senior_level
27,Production Modeling Corporation,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
28,Mentor Graphics,"Fremont, CA 94538 (Irvington area)",75000.0,Data_Analyst,Senior_level
29,Sutter Health,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Credit Karma,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
76,CSI Consulting,"San Jose, CA",75000.0,Data_Analyst,Senior_level
77,Adroit Resources Inc,"Fremont, CA 94539 (Cameron Hills area)",75000.0,Data_Analyst,Senior_level
78,AllianceIT,"San Ramon, CA",75000.0,Data_Analyst,Senior_level
79,Symantec,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
80,Symantec,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
81,Proofpoint,"Sunnyvale, CA 94089",75000.0,Data_Analyst,Senior_level
82,Catalina Marketing,"San Jose, CA",75000.0,Data_Analyst,Senior_level
83,GE Careers,"San Ramon, CA 94583",75000.0,Data_Analyst,Senior_level
84,TEKsystems,"San Francisco, CA 94103 (South Of Market area)",75000.0,Data_Analyst,Senior_level
85,Sony Interactive Entertainment PlayStation,"San Mateo, CA",75000.0,Data_Analyst,Senior_level
86,Quantifind,"Menlo Park, CA",75000.0,Data_Analyst,Senior_level
87,Silicon Valley Bank,"Santa Clara, CA 95054",75000.0,Data_Analyst,Senior_level
88,Uber,"Palo Alto, CA 94304",75000.0,Data_Analyst,Senior_level
89,Dolby,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
90,Wells Fargo,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
91,Visa,"Foster City, CA",75000.0,Data_Analyst,Senior_level
92,Blue Shield of California,"San Francisco, CA 94105 (Financial District area)",75000.0,Data_Analyst,Senior_level
93,ConnectPoint Search Group,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
94,MINDTREE,"San Francisco, CA",75000.0,Data_Analyst,Senior_level
95,Sony Interactive Entertainment PlayStation,"San Mateo, CA",75000.0,Data_Analyst,Senior_level
96,TrialPay,"Mountain View, CA",75000.0,Data_Analyst,Senior_level
97,Paypal,"San Jose, CA",75000.0,Data_Analyst,Senior_level
98,"InfoVision, Inc.","San Jose, CA",75000.0,Data_Analyst,Senior_level
99,Elevate Recruiting Group,"Palo Alto, CA",75000.0,Data_Analyst,Senior_level
100,Tesla Motors,"Newark, CA",75000.0,Data_Analyst,Senior_level
101,Plex,"Pleasanton, CA",75000.0,Data_Analyst,Senior_level
102,Dell,"Santa Clara, CA",75000.0,Data_Analyst,Senior_level
103,Genentech,"South San Francisco, CA",75000.0,Data_Analyst,Senior_level
104,Uber,"San Francisco, CA 94105",75000.0,Data_Analyst,Senior_level

In [116]:
## Data_Analyst_SF_85_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=San+Francisco,+CA&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_85_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_85_entry

## Data_Analyst_SF_85_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=San+Francisco,+CA&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_85_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_85_mid

## Data_Analyst_SF_85_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$85,000&l=San+Francisco,+CA&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 85000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_85_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_85_senior

,Company_name,Location,Salary,Title,Experience
0,Freedom Financial Network,"San Mateo, CA 94402",85000.0,Data_Analyst,Senior_level
1,Genentech,"South San Francisco, CA",85000.0,Data_Analyst,Senior_level
2,intuit,"Mountain View, CA 94043",85000.0,Data_Analyst,Senior_level
3,iSoft Solutions,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
4,Genentech,"South San Francisco, CA",85000.0,Data_Analyst,Senior_level
5,"Cisco Systems, Inc.","San Jose, CA",85000.0,Data_Analyst,Senior_level
6,Athleta,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
7,Intuit,"Mountain View, CA 94039",85000.0,Data_Analyst,Senior_level
8,Nuna,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
9,Google,"Mountain View, CA",85000.0,Data_Analyst,Senior_level
10,Manage,"Mountain View, CA",85000.0,Data_Analyst,Senior_level
11,Capital One,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
12,RichRelevance,"San Francisco, CA 94111 (Financial District area)",85000.0,Data_Analyst,Senior_level
13,Intel,"Santa Clara, CA 95052",85000.0,Data_Analyst,Senior_level
14,Capital One,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
15,Hired,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
16,GE Careers,"San Ramon, CA 94583",85000.0,Data_Analyst,Senior_level
17,Genentech,"South San Francisco, CA",85000.0,Data_Analyst,Senior_level
18,University of California Office of the...,"Oakland, CA 94607 (Acorn-Acorn Industrial area)",85000.0,Data_Analyst,Senior_level
19,CA Technologies,"Santa Clara, CA",85000.0,Data_Analyst,Senior_level
20,MachineZone,"Palo Alto, CA",85000.0,Data_Analyst,Senior_level
21,Arthur Lawrence,"Sunnyvale, CA",85000.0,Data_Analyst,Senior_level
22,City & County of San Francisco,"San Francisco, CA 94124 (Bayview area)",85000.0,Data_Analyst,Senior_level
23,Poshmark,"Redwood City, CA",85000.0,Data_Analyst,Senior_level
24,Production Modeling Corporation,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
25,Mentor Graphics,"Fremont, CA 94538 (Irvington area)",85000.0,Data_Analyst,Senior_level
26,Sutter Health,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
27,Roche,"Santa Clara, CA",85000.0,Data_Analyst,Senior_level
28,Symantec,"Mountain View, CA",85000.0,Data_Analyst,Senior_level
29,Change.org,"San Francisco, CA 94103 (South Of Market area)",85000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Dolby,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
76,Wells Fargo,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
77,Visa,"Foster City, CA",85000.0,Data_Analyst,Senior_level
78,MINDTREE,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
79,TrialPay,"Mountain View, CA",85000.0,Data_Analyst,Senior_level
80,Paypal,"San Jose, CA",85000.0,Data_Analyst,Senior_level
81,"InfoVision, Inc.","San Jose, CA",85000.0,Data_Analyst,Senior_level
82,Elevate Recruiting Group,"Palo Alto, CA",85000.0,Data_Analyst,Senior_level
83,Tesla Motors,"Newark, CA",85000.0,Data_Analyst,Senior_level
84,Plex,"Pleasanton, CA",85000.0,Data_Analyst,Senior_level
85,Dell,"Santa Clara, CA",85000.0,Data_Analyst,Senior_level
86,Demandbase,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
87,RideCell,"San Francisco, CA 94103 (South Of Market area)",85000.0,Data_Analyst,Senior_level
88,Workbridge Associates,"San Francisco, CA 94105 (Financial District area)",85000.0,Data_Analyst,Senior_level
89,Trulia,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
90,Chegg,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
91,Netflix,"Los Gatos, CA",85000.0,Data_Analyst,Senior_level
92,Apple,"Santa Clara Valley, CA",85000.0,Data_Analyst,Senior_level
93,Medallia Inc,"Palo Alto, CA 94306 (Barron Park area)",85000.0,Data_Analyst,Senior_level
94,SAP,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
95,Clorox,"Oakland, CA 94612 (Northgate area)",85000.0,Data_Analyst,Senior_level
96,Intel,"San Jose, CA 95125 (Willow Glen area)",85000.0,Data_Analyst,Senior_level
97,Apple,"Santa Clara Valley, CA",85000.0,Data_Analyst,Senior_level
98,University of California San Francisco...,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
99,Arka,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
100,Adobe,"San Jose, CA",85000.0,Data_Analyst,Senior_level
101,"Solutionary, Inc.","East Palo Alto, CA",85000.0,Data_Analyst,Senior_level
102,EY,"San Francisco, CA",85000.0,Data_Analyst,Senior_level
103,Kforce,"Oakland, CA 94612",85000.0,Data_Analyst,Senior_level
104,Stanford Health Care,"Palo Alto, CA 94305",85000.0,Data_Analyst,Senior_level

In [117]:
## Data_Analyst_SF_100_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=San+Francisco,+CA&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_100_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_100_entry

## Data_Analyst_SF_100_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=San+Francisco,+CA&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_100_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_100_mid

## Data_Analyst_SF_100_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$100,000&l=San+Francisco,+CA&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 100000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_100_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_100_senior

,Company_name,Location,Salary,Title,Experience
0,Freedom Financial Network,"San Mateo, CA 94402",100000.0,Data_Analyst,Senior_level
1,Genentech,"South San Francisco, CA",100000.0,Data_Analyst,Senior_level
2,ServiceNow,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
3,iSoft Solutions,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
4,"Cisco Systems, Inc.","San Jose, CA",100000.0,Data_Analyst,Senior_level
5,Symantec,"Mountain View, CA",100000.0,Data_Analyst,Senior_level
6,Intuit,"Mountain View, CA 94039",100000.0,Data_Analyst,Senior_level
7,Nuna,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
8,Fitbit,"San Francisco, CA 94105 (Financial District area)",100000.0,Data_Analyst,Senior_level
9,Google,"Mountain View, CA",100000.0,Data_Analyst,Senior_level
10,Capital One,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
11,Dolby,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
12,RichRelevance,"San Francisco, CA 94111 (Financial District area)",100000.0,Data_Analyst,Senior_level
13,"Cisco Systems, Inc.","Santa Clara, CA",100000.0,Data_Analyst,Senior_level
14,Intel,"Santa Clara, CA 95052",100000.0,Data_Analyst,Senior_level
15,Capital One,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
16,Hired,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
17,Genentech,"South San Francisco, CA",100000.0,Data_Analyst,Senior_level
18,GE Careers,"San Ramon, CA 94583",100000.0,Data_Analyst,Senior_level
19,"InfoVision, Inc.","San Jose, CA",100000.0,Data_Analyst,Senior_level
20,Apple,"Santa Clara Valley, CA",100000.0,Data_Analyst,Senior_level
21,City & County of San Francisco,"San Francisco, CA 94124 (Bayview area)",100000.0,Data_Analyst,Senior_level
22,Arka,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
23,MachineZone,"Palo Alto, CA",100000.0,Data_Analyst,Senior_level
24,Production Modeling Corporation,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
25,Mentor Graphics,"Fremont, CA 94538 (Irvington area)",100000.0,Data_Analyst,Senior_level
26,Genentech,"South San Francisco, CA",100000.0,Data_Analyst,Senior_level
27,Google,"Mountain View, CA",100000.0,Data_Analyst,Senior_level
28,Astreya,"Sunnyvale, CA",100000.0,Data_Analyst,Senior_level
29,Fitbit,"San Francisco, CA 94105 (Financial District area)",100000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Veear Projects,"Palo Alto, CA",100000.0,Data_Analyst,Senior_level
76,Paypal,"San Jose, CA",100000.0,Data_Analyst,Senior_level
77,Elevate Recruiting Group,"Palo Alto, CA",100000.0,Data_Analyst,Senior_level
78,Plex,"Pleasanton, CA",100000.0,Data_Analyst,Senior_level
79,Dell,"Santa Clara, CA",100000.0,Data_Analyst,Senior_level
80,TrialPay,"Mountain View, CA",100000.0,Data_Analyst,Senior_level
81,RideCell,"San Francisco, CA 94103 (South Of Market area)",100000.0,Data_Analyst,Senior_level
82,Demandbase,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
83,Workbridge Associates,"San Francisco, CA 94105 (Financial District area)",100000.0,Data_Analyst,Senior_level
84,Chegg,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
85,Clorox,"Oakland, CA 94612 (Northgate area)",100000.0,Data_Analyst,Senior_level
86,Apple,"Santa Clara Valley, CA",100000.0,Data_Analyst,Senior_level
87,University of California San Francisco...,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
88,Netflix,"Los Gatos, CA",100000.0,Data_Analyst,Senior_level
89,SAP,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
90,Adobe,"San Jose, CA",100000.0,Data_Analyst,Senior_level
91,Apartment List,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
92,"Solutionary, Inc.","East Palo Alto, CA",100000.0,Data_Analyst,Senior_level
93,Capgemini,"South San Francisco, CA",100000.0,Data_Analyst,Senior_level
94,Peet's Coffee & Tea,"Emeryville, CA 94608",100000.0,Data_Analyst,Senior_level
95,Vivo,"San Francisco, CA 94123 (Marina area)",100000.0,Data_Analyst,Senior_level
96,Blue Shield of California,"San Francisco, CA 94105 (Financial District area)",100000.0,Data_Analyst,Senior_level
97,Zendesk,"San Francisco, CA 94103 (South Of Market area)",100000.0,Data_Analyst,Senior_level
98,IMVU,"Redwood City, CA",100000.0,Data_Analyst,Senior_level
99,Gap Inc. Corporate,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
100,Visa,"Foster City, CA",100000.0,Data_Analyst,Senior_level
101,Verifone,"San Jose, CA",100000.0,Data_Analyst,Senior_level
102,First Republic Bank,"San Francisco, CA",100000.0,Data_Analyst,Senior_level
103,intuit,"Mountain View, CA 94043",100000.0,Data_Analyst,Senior_level
104,Genentech,"South San Francisco, CA",100000.0,Data_Analyst,Senior_level

In [118]:
## Data_Analyst_SF_115_entry

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=San+Francisco,+CA&radius=50&explvl=entry_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Entry_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_115_entry = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_115_entry

## Data_Analyst_SF_115_mid

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=San+Francisco,+CA&radius=50&explvl=mid_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Mid_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_115_mid = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_115_mid

## Data_Analyst_SF_115_senior

driver = webdriver.Chrome()
url = "https://www.indeed.com/jobs?q=data+analyst+$115,000&l=San+Francisco,+CA&radius=50&explvl=senior_level&limit=100"
driver.get(url)
# wait one second
sleep(1)
#grab the page source
html = driver.page_source
# BeautifulSoup it!
html = BeautifulSoup(html)
driver.close()

# I'm going to create my empty df first
import pandas as pd
dcarea_job1 = pd.DataFrame(columns=["Company_name"])
dcarea_job2 = pd.DataFrame(columns=["Location","Salary", "Title","Experience"])
# loop through each entry
for company in html.find_all('span', {'class':'company'}):
    name_comp = company.text
    dcarea_job1.loc[len(dcarea_job1)]=[name_comp]
    
for location in html.find_all('span', {'class':'location'}):
    loc_comp = location.text
    salary = 115000
    experience = "Senior_level"
    # try to find the number of bookings
    title = "Data_Analyst"
    dcarea_job2.loc[len(dcarea_job2)]=[loc_comp,salary,title,experience]

dcarea_job1['Company_name'] = dcarea_job1['Company_name'].str.replace('\n', '')
dcarea_job2['Location'] = dcarea_job2['Location'].str.replace('\n', '')

result_SF_115_senior = pd.concat([dcarea_job1, dcarea_job2], axis=1)

result_SF_115_senior

,Company_name,Location,Salary,Title,Experience
0,Freedom Financial Network,"San Mateo, CA 94402",115000.0,Data_Analyst,Senior_level
1,BayOne Solutions,"San Francisco, CA 94107",115000.0,Data_Analyst,Senior_level
2,"Controller's Group, Inc.","Mountain View, CA",115000.0,Data_Analyst,Senior_level
3,iSoft Solutions,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
4,"Cisco Systems, Inc.","San Jose, CA",115000.0,Data_Analyst,Senior_level
5,Google,"Mountain View, CA",115000.0,Data_Analyst,Senior_level
6,Hired,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
7,Capital One,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
8,GE Careers,"San Ramon, CA 94583",115000.0,Data_Analyst,Senior_level
9,MachineZone,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
10,Mentor Graphics,"Fremont, CA 94538 (Irvington area)",115000.0,Data_Analyst,Senior_level
11,Change.org,"San Francisco, CA 94103 (South Of Market area)",115000.0,Data_Analyst,Senior_level
12,Production Modeling Corporation,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
13,GE Careers,"San Ramon, CA 94583",115000.0,Data_Analyst,Senior_level
14,Symantec,"Mountain View, CA",115000.0,Data_Analyst,Senior_level
15,Sephora,"San Francisco, CA 94105 (Financial District area)",115000.0,Data_Analyst,Senior_level
16,Salesforce,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
17,Gap Inc. Corporate,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
18,Bank of the West,"San Ramon, CA",115000.0,Data_Analyst,Senior_level
19,BNP Paribas,"San Ramon, CA",115000.0,Data_Analyst,Senior_level
20,TEKsystems,"San Francisco, CA 94103 (South Of Market area)",115000.0,Data_Analyst,Senior_level
21,Gap Inc. Corporate,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
22,eBay,"San Jose, CA",115000.0,Data_Analyst,Senior_level
23,eBay,"San Jose, CA",115000.0,Data_Analyst,Senior_level
24,Fitbit,"San Francisco, CA 94105 (Financial District area)",115000.0,Data_Analyst,Senior_level
25,Bayone Solutions Inc.,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
26,eBay,"San Jose, CA",115000.0,Data_Analyst,Senior_level
27,Dolby,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
28,Credit Karma,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
29,ZS Associates,"San Mateo, CA 94402 (Beresford area)",115000.0,Data_Analyst,Senior_level
...,...,...,...,...,...
75,Samsung Electronics America,"Mountain View, CA",115000.0,Data_Analyst,Senior_level
76,Oracle,"Redwood City, CA",115000.0,Data_Analyst,Senior_level
77,Silicon Valley Bank,"Santa Clara, CA 95054",115000.0,Data_Analyst,Senior_level
78,Google,"Mountain View, CA",115000.0,Data_Analyst,Senior_level
79,Infoyogi,"San Jose, CA",115000.0,Data_Analyst,Senior_level
80,Intuit,"Mountain View, CA 94039",115000.0,Data_Analyst,Senior_level
81,Sephora,"San Francisco, CA 94105 (Financial District area)",115000.0,Data_Analyst,Senior_level
82,Chegg,"Santa Clara, CA 95054",115000.0,Data_Analyst,Senior_level
83,Equinix,"Redwood City, CA 94065",115000.0,Data_Analyst,Senior_level
84,"Cisco Systems, Inc.","San Jose, CA",115000.0,Data_Analyst,Senior_level
85,Weebly,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
86,Autodesk,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
87,HyperGrid,"Mountain View, CA",115000.0,Data_Analyst,Senior_level
88,Affirm,"San Francisco, CA 94126 (Financial District area)",115000.0,Data_Analyst,Senior_level
89,Netflix,"Los Gatos, CA",115000.0,Data_Analyst,Senior_level
90,Evernote,"Redwood City, CA 94063",115000.0,Data_Analyst,Senior_level
91,SanDisk,"Milpitas, CA",115000.0,Data_Analyst,Senior_level
92,쿠팡,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
93,BOLD,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
94,"Controller's Group, Inc.","Mountain View, CA",115000.0,Data_Analyst,Senior_level
95,Netflix,"Los Gatos, CA",115000.0,Data_Analyst,Senior_level
96,Workbridge Associates,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
97,Proofpoint,"Sunnyvale, CA 94089",115000.0,Data_Analyst,Senior_level
98,Sigmaways,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
99,Accenture,"San Francisco, CA 94105 (Financial District area)",115000.0,Data_Analyst,Senior_level
100,Coupang,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
101,쿠팡,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
102,쿠팡,"Palo Alto, CA",115000.0,Data_Analyst,Senior_level
103,CyberCoders,"San Francisco, CA",115000.0,Data_Analyst,Senior_level
104,intuit,"Mountain View, CA 94043",115000.0,Data_Analyst,Senior_level

## Data Analyst dataset

In [121]:
result_DC_Data_Analyst = pd.concat([result_DC_60_entry,result_DC_60_mid,result_DC_60_senior,result_DC_70_entry,result_DC_70_mid,result_DC_70_senior,result_DC_75_entry,result_DC_75_mid,result_DC_75_senior,result_DC_85_entry,result_DC_85_mid,result_DC_85_senior,result_DC_100_entry,result_DC_100_mid,result_DC_100_senior])

In [122]:
result_DC_Data_Analyst.shape

(1575, 5)

In [123]:
result_NY_Data_Analyst = pd.concat([result_NY_55_entry,result_NY_55_mid,result_NY_55_senior,result_NY_70_entry,result_NY_70_mid,result_NY_70_senior,result_NY_85_entry,result_NY_85_mid,result_NY_85_senior,result_NY_95_entry,result_NY_95_mid,result_NY_95_senior,result_NY_115_entry,result_NY_115_mid,result_NY_115_senior])

In [126]:
result_NY_Data_Analyst.shape

(1575, 5)

In [127]:
result_SF_Data_Analyst = pd.concat([result_SF_60_entry,result_SF_60_mid,result_SF_60_senior,result_SF_75_entry,result_SF_75_mid,result_SF_75_senior,result_SF_85_entry,result_SF_85_mid,result_SF_85_senior,result_SF_100_entry,result_SF_100_mid,result_SF_100_senior,result_SF_115_entry,result_SF_115_mid,result_SF_115_senior])

In [128]:
result_SF_Data_Analyst.shape

(1575, 5)

In [130]:
result_SF_Data_Analyst.to_csv('result_SF_Data_Analyst.csv', encoding='utf-8')

In [131]:
result_NY_Data_Analyst.to_csv('result_NY_Data_Analyst.csv', encoding='utf-8')

In [132]:
result_DC_Data_Analyst.to_csv('result_DC_Data_Analyst.csv', encoding='utf-8')

In [133]:
result_Data_Analyst = pd.concat([result_DC_Data_Analyst,result_NY_Data_Analyst,result_SF_Data_Analyst])

In [134]:
result_Data_Analyst.shape

(4725, 5)

In [135]:
result_Data_Analyst.to_csv('result_Data_Analyst.csv', encoding='utf-8')